### ISSUE TITLE
Roles and Access control lists

### ISSUE THREAD

**Issue by Raulken** [sonata-project/SonataAdminBundle#1097]
i read this documentation
http://www.sonata-project.org/bundles/admin/master/doc/reference/security.html
and i have generate correctly the roles for my admin class

the problem is, if i set one user with role ROLE_SONATA_USER_ADMIN_USER_ADMIN and after i make the switch to that user, and i go in admin/dashboard , i not see the panel for user....i see only white page.... why?

``` yml

    acl:
        connection: default 

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#        SONATA:
#            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented



sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
        # role security information
        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            VIEW: VIEW
            DELETE: DELETE
            EXPORT: EXPORT
            OPERATOR: OPERATOR
            MASTER: MASTER

        handler: sonata.admin.security.handler.acl
            # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]

```
