### ISSUE TITLE
SF 2.2 - Ajax layout not called

### ISSUE THREAD

**Issue by EnergieZ** [sonata-project/SonataAdminBundle#1233]
Hi,

Since SF2.2, ajax layout define in config.yml is not called any more !

Here is my config : 

Config.yml

``` yaml
sonata_admin:
    title:      Test Administration
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        layout:  TestCnffBundle:Admin:sonata_standard_layout.html.twig
        ajax:    TestCnffBundle:Admin:ajax_layout.html.twig
        dashboard: SonataAdminBundle:Core:dashboard.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
```

The "global" layout is called, but not the ajax one !

ajax_layout.html.twig

``` twig
{% block content %}
    {{ parent() }}

    <script type="text/javascript">
        $(document).ready(function() {
            $('.datepicker').datepicker();
            $.fn.sort_select_box = function(){
                // Get options from select box
                var selected = $(this).val();
                console.log(selected);
                var my_options = $("#" + this.attr('id') + ' option');
                // sort alphabetically
                my_options.sort(function(a,b) {
                    if (a.text > b.text) return 1;
                    else if (a.text < b.text) return -1;
                    else return 0
                })
                //replace with sorted my_options;
                $(this).empty().append( my_options );

                // clearing any selections
                $("#"+this.attr('id')+" option").attr('selected', false);
                $(this).val(selected);
            }
            $('.chosen').sort_select_box();
            $(".chosen").data("placeholder","Cliquez pour sélectionner...").chosen();
        });
    </script>
    {{ tinymce_init() }}
{% endblock %}
```

Tryed this with an ajax alert('test'); and does not work. Same with an < h1>test< /h1>
