### ISSUE TITLE
Couldn't connect to admin/dashboard

### ISSUE THREAD

**Issue by zmaximov** [sonata-project/SonataAdminBundle#1235]
I've installed SonataAdminBundle, SonataDoctrineORMAdminBundle() and SimpleThingsEntityAuditBundle, config routing.yml:

```
admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
```

But when I try to connect http://localhost/symfony/web/app_dev.php/admin I've got:

`No route found for "GET /admin"
404 Not Found - NotFoundHttpException
1 linked Exception: ResourceNotFoundException`

If http://localhost/symfony/web/app_dev.php/admin/dashboard redirect to http://localhost/symfony/web/app_dev.php/login
