### ISSUE TITLE
[Documentation] - Update dashboard block for Sonata Admin Bundles

### ISSUE THREAD

**Issue by Maxwell2022** [sonata-project/SonataAdminBundle#1286]
Trying to customize the user block in the dashboard. I'm following the exemple from http://sonata-project.org/bundles/admin/2-1/doc/reference/dashboard.html 
(the first configuration block is incorrect, `blocks` should be under `dashboard`). I'm trying to update the label just to see if it's working as expected:

```yaml
sonata_admin:
    title: Acme Administration
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

        groups:
            sonata_user:
                label: Acme User
```

And none of the blocks are showing now. I have no errors in the logs, neither on the page.
Not sure what's happening.

My goal was to display few stats in the dashboard, such as today's stats (number of login, number of new users). But I can't even manage to change the label of the block.

Maxime
