### ISSUE TITLE
Route "admin_sf2mcq_core_category_create" does not exist

### ISSUE THREAD

**Issue by djpate** [sonata-project/SonataAdminBundle#133]
I'm trying to setup a basic admin but I'm stuck on that error :

```
An exception has been thrown during the rendering of a template ("Route "admin_sf2mcq_core_category_create" does not exist.") in SonataAdminBundle:Core:dashboard.html.twig at line 30. 
```

I believe I followed the tutorial carefully.

Here is my configuration

```
services:
   sf2mcq.core.admin.category:
      class: Sf2MCQ\CoreBundle\Admin\CategoryAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: sonata_blog, label: category }
      arguments: [null, Sf2MCQ\CoreBundle\Entity\Category, Sf2MCQCoreBundle:CategoryAdmin]
```

Is is not clear to me If I have to change things in the tags field. name: foo fixes the issue but display nothing in the admin area...
