### ISSUE TITLE
Exception is thrown when dashboard groups are set in positions

### ISSUE THREAD

**Issue by siciarek** [sonata-project/SonataAdminBundle#1332]
sonata_admin:
    dashboard
        blocks:
            # display two dashboard blocks
            - { position: left,  type: sonata.admin.block.admin_list, settings: { groups: [sonata_page1, sonata_page2] } }
            - { position: right, type: sonata.admin.block.admin_list, settings: { groups: [sonata_page3] } }

```
    groups:
        sonata_page1:
            items:
                - sonata.page.admin.myitem1
        sonata_page2:
            items:
                - sonata.page.admin.myitem2
                - sonata.page.admin.myitem3
        sonata_page3:
            items:
```

Throws exception:

An exception has been thrown during the rendering of a template ("exception 'Symfony\Component\OptionsResolver\Exception\InvalidOptionsException' with message 'The option "groups" with value "Array" is expected to be of type "bool"' in F:\Workspace\sandbox\vendor\symfony\symfony\src\Symfony\Component\OptionsResolver\OptionsResolver.php:338
