### ISSUE TITLE
ACL: CREATE implies EDIT

### ISSUE THREAD

**Issue by BraisGabin** [sonata-project/SonataAdminBundle#1334]
I'm configuring my Sonata admin permissions. If I write this in `app/config/config.yml`:
```yml
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            STAFF:    [EDIT]
```
The users with this role only can edit. But if I write this:
```yml
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            STAFF:    [CREATE]
```
The users can edit and create. Is this correct? Is it a bug? I only would want give creation permission and not edit.
