### ISSUE TITLE
Custom voter no ACL - No object received

### ISSUE THREAD

**Issue by Glideh** [sonata-project/SonataAdminBundle#1458]
I'm using SonataAdmin with `sonata.admin.security.handler.role` (so I don't use ACLs here).

I'm trying to restrict access to an object with a custom voter.

**service**

``` yml
security.access.company_voter:
    class:     My\Voter\Class
    public:     false
    tags:
       - { name: security.voter }
```

**voter** _My\Voter\Class.php_

``` php
#...
public function vote(TokenInterface $token, $object, array $attributes) 
{
    $object;
    # $object is always NULL
}
#...
```

But I'm always getting NULL as `$object`.

What could be the reason ?

---

The context is _CRUD/base_edit.html.twig_ and _CRUD/list__action_edit.html.twig_

``` html
<div class="sonata-actions">
    ... admin.isGranted('VIEW', object) ...
</div>
{% if admin.isGranted('EDIT', object) ...
    <a href="..." class="edit_link">...</a>
{% endif %}
```
