### ISSUE TITLE
Create an extension does not work

### ISSUE THREAD

**Issue by Chrysweel** [sonata-project/SonataAdminBundle#1658]
Hi.

I want to create an extension but nothing happens.

I created my service:

```
    my.sonata.admin.extension:
        class: MyProject\AdminBundle\AdminExtension\MediaAdminExtension
        tags:
            - { name: sonata.admin.extension, target: sonata.media.admin.media.class }
```

And my extension:

```
use Sonata\AdminBundle\Admin\AdminExtensionInterface;
use Sonata\AdminBundle\Admin\AdminExtension;
use Sonata\AdminBundle\Form\FormMapper;

class MediaAdminExtension extends AdminExtension implements AdminExtensionInterface
{
     /**
     * {@inheritdoc}
     */
    public function configureFormFields(FormMapper $form)
    {
      ldd('hola');   // I use the bundle LadyBug
     }
}
```

I also tried with service:

```
    sonata.admin.extension:
        class: Ant\WebChatea\AdminBundle\AdminExtension\MediaAdminExtension
        tags:
            - { name: sonata.admin.extension, global:true }
```

And nothing happens!!

I did all same that documentation http://sonata-project.org/bundles/admin/master/doc/reference/extensions.html somebody knows what happen?
