### ISSUE TITLE
SonataAdminBundle - Many to many relation problem.

### ISSUE THREAD

**Issue by lvarayut** [sonata-project/SonataAdminBundle#1876]
I'm trying to create a Many-to-Many relation between Users and Roles entities. So, I use Users.orm.yml and Roles.orm.yml in order to separate ORM from entity classes.

```
Users.orm.yml
```

``` yml
Acme\Bundle\DemeBundle\Entity\Users:
    type: entity
    table: Users
    id:
        Id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        Name:
            type: string
            length: 30
        LastName:
            type: string
            length: 30
        Email:
            type: string
            length: 60
            unique: true
        Username:
            type: string
            length: 10
            unique: true
        Password:
            type: string
            length: 100
            unique: false
        DateCreated:
            type: datetime
    manyToMany:
        Roles:
            targetEntity: Roles
            mappedBy: Users

    lifecycleCallbacks:
        prePersist: [ setDateCreatedValue ]
```

```
Roles.orm.yml
```

``` yml
Acme\Bundle\DemoBundle\Entity\Roles:
    type: entity
    table: Roles
    id:
        Id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        Name:
            type: string
            length: 60
            unique: true
        Description:
            type: string
            length: 250
            unique: true
        DateCreated:
            type: datetime
    manyToMany:
        Users:
            targetEntity: Users
            joinTable:
                name: Users_Roles
                joinColumns:
                    UserId:
                        referencedColumnName: Id
                inverseJoinColumns:
                    RoleId:
                        referencedColumnName: Id
    lifecycleCallbacks:
        prePersist: [ setDateCreatedValue ]
```

From these ORM, I generated the Users and Roles entities. I also updated the schema in MySQL. So, I got three tables - Users, Roles, and Users_Roles.

Now, I created a back-end dashboard for Admin by using SonataAdminBundle. I mapped the fileds as following :

``` php
namespace Acme\Bundle\DemoBundle\Administrator;
class UsersAdmin extends Admin
{
    // Fields to be shown on create/edit forms
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('Name', 'text', array('label' => 'Name'))
            ->add('LastName', 'text', array('label' => 'Last name'))
            ->add('Email') //if no type is specified, SonataAdminBundle tries to guess it
            ->add('Username')
            ->add('Password')
            ->add('Roles','sonata_type_model',array('required' => false,'expanded' => true,'by_reference' => false))
    ;
    }
}
```

When I run the dashboard, It always return Catchable Fatal Error: Object of class Acme\Bundle\DemoBundle\Entity\Roles could not be converted to string.

I think that the problem could occur because of the mapping files - orm.yml. However, I don't know which part causes the error.
