### ISSUE TITLE
Unable to found a valid admin for the class: ABC\Entity\User, get too many admin registered

### ISSUE THREAD

**Issue by ideea** [sonata-project/SonataAdminBundle#1909]
Hello. i have a problem with some latest sonata.

I have two services/admin classes to edit users. Clients and Admins separately.

Before few updates it was ok and now i have exception:

> ```
> Unable to found a valid admin for the class: ABC\Entity\User, get too many admin registered:
> abc.platform.admin.administrators,abc.platform.admin.users
> 500 Internal Server Error - RuntimeException
> ```

```
abc.platform.admin.administrators:
          class: ABC\PlatformBundle\Admin\AdministratorsAdmin
          arguments: [null, ABC\Entity\User, null]
          calls:
              - [ setUserManager, [@fos_user.user_manager]]
              - [ addChild, [ @abc.platform.admin.bookmark ] ]
              - [ addChild, [ @abc.platform.admin.folder ] ]
          tags:
              - { name: sonata.admin, show_in_dashboard: true , manager_type: orm, group: %sonata.user.admin.groupname%, label: 'Admins' }

abc.platform.admin.users:
    class: ABC\PlatformBundle\Admin\UserAdmin
    arguments: [null, ABC\Entity\User, null]
    calls:
        - [ setUserManager, [@fos_user.user_manager]]
        - [ addChild, [ @abc.platform.admin.bookmark ] ]
        - [ addChild, [ @abc.platform.admin.folder ] ]
    tags:
        - { name: sonata.admin, show_in_dashboard: false , manager_type: orm, group: %sonata.user.admin.groupname%, label: 'Clients' }
```
