### ISSUE TITLE
question about admin extension

### ISSUE THREAD

**Issue by ElectricMaxxx** [sonata-project/SonataAdminBundle#2046]
Hi, 

i got an issue with the registration of my admin extension, but i will show the example:
mapping:
```
        <service id="cmf_seo.admin_extension" class="%cmf_seo.admin_extension.class%">
            <tag name="sonata.admin.extension" />
        </service>
```
config:
```
sonata_admin:
    extensions:
        cmf_seo.admin_extension:
            implements:
                - Symfony\Cmf\Bundle\SeoBundle\Model\SeoAwareInterface
```
This should react on all classes that implement the `SeoAwareInterface`, right?

But it does not in my case. I got a an inheritence like.

``` 
class DemoClass extends BaseClass inherit SeoAwareInterface
{
....
}
```

and build an admit for the `BaseClass`. If i open the admin i do not see the action the extension should do. If i do it direct it works.
