### ISSUE TITLE
`SubEnittyAdmin` has incorrect `parent` parameter

### ISSUE THREAD

**Issue by bm13kk** [sonata-project/SonataAdminBundle#2077]
I have problem creating embedded entity form.

Shortly i need make working next connection: Subscription (parent) <- SubscriptionVariant (child). And when i creating embedded form "add child" button redirect to `admin\subscriptionvariant\create`, not to  `admin\subscription\{id}\subscriptionvariant\create`.
List of embedded fields displaying correctly. Everything is working, except this `add button` 

Config:

``` yml
sonata.admin.subscription:
    class: XXX\AdminBundle\Admin\SubscriptionAdmin
    arguments: [~, XXX\CommonBundle\Entity\Subscription, ~]
    tags:
        - { name: sonata.admin, manager_type: orm, group: "XXX", label: "Subscription" }
    calls:
        - [ addChild, [@sonata.admin.subscription_variant] ]

sonata.admin.subscription_variant:
    class: XXX\AdminBundle\Admin\SubscriptionVariantAdmin
    arguments:  [~, XXX\CommonBundle\Entity\SubscriptionVariant, ~]
    tags:
        - { name: sonata.admin, manager_type: orm, group: "XXX", label: "SubscriptionVariant" }
```

Subscription:

``` php
class SubscriptionAdmin extends Admin
{
    ...
    /**
     * {@inheritdoc}
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('id', null, ['disabled' => true])
            ...
            ->add('subscriptionVariants', 'sonata_type_collection', [
                    'by_reference' => true,
                    'label'        => 'Variants',
                    'type_options' => ['delete' => false],
                    'btn_add'      => 'some link',
                ], [
                    'edit'     => 'inline',
                    'inline'   => 'table',
                    'sortable' => 'id',
                ]
            )
        ;
    }
}
```

SubscriptionVariant:

``` php
class SubscriptionVariantAdmin extends Admin
{
    protected $parentAssociationMapping = 'subscription';

    /**
     * {@inheritdoc}
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('field1')
            ->add('field2')
            ->remove('_delete')
        ;
    }
}
```

While debugging it, i found, that `SubscriptionVariant` class created 4(!) times. And in moment of creating "add child" button `SubscriptionVariantAdmin->parent` is empty.
