### ISSUE TITLE
Please document setTemplates option in service config

### ISSUE THREAD

**Issue by codecowboy** [sonata-project/SonataAdminBundle#2098]
From the docs:

A setTemplates(array $templates) (notice the plural) function also exists, that allows you to set multiple templates at once. Notice that, if used outside of the service definition context, setTemplates(array $templates) will replace the whole template list for that Admin class, meaning you have to explicitly pass the full template list in the $templates argument.
```
Please someone provide the yaml config required to use setTemplates?

services:
    sonata.admin.myadmin:
      class: MyNamespace\Bundle\AdminBundle\Tools\MyAdmin
      tags:
          - { name: sonata.admin, manager_type: orm, group: "Tools", label: "MyAdmin" }
      arguments:
...
      calls:
          - [ setTemplates, ??? ]
```
