### ISSUE TITLE
sonata_type_date_picker not loaded

### ISSUE THREAD

**Issue by tranthienbinh1989** [sonata-project/SonataAdminBundle#2175]
I'm using sonata adminbundle : dev-master and corebundle : dev-master.
So when I create field with sonata_type_date_picker . The form can not load html template for this field.

**Comment by logansam** [comment]
I am having the same issue. 
     ->add('publishedAt', 'sonata_type_datetime_picker', array(
                    'dp_use_current'        => false,
                    'dp_use_seconds'        => false,
                    'required'              => false,
                    'label'                 => 'Published At'
                ))

**Comment by pulzarraider** [comment]
Did you try to add `SonataCoreBundle:Form:datepicker.html.twig` in Tewig resources in app/config.yml as it's [described in the documentation](http://sonata-project.org/bundles/core/master/doc/reference/form_types.html#sonata-type-date-picker-and-sonata-type-datetime-picker)?

```
# app/config.yml
twig:
    # ...
    form:
        resources:
            # ...
            - 'SonataCoreBundle:Form:datepicker.html.twig'
```
