### ISSUE TITLE
too many admin registered

### ISSUE THREAD

**Issue by trq** [sonata-project/SonataAdminBundle#2212]
When trying to create/edit a Page, I get an error regarding the related Category entity.

I have looked at #1899, #1906, #1909 and have tried to apply the same fix. In my case, its not working because "admin_code" does not get passed through to Admin::attachAdminClass.

My error:
```
Unable to found a valid admin for the class: Foo\SiteBundle\Entity\Category, get too many admin registered: sonata.domain.site.mainmenu,sonata.domain.site.secondarymenu
```

Stack Trace:
```
[1] RuntimeException: Unable to found a valid admin for the class: Foo\SiteBundle\Entity\Category, get too many admin registered: sonata.domain.site.mainmenu,sonata.domain.site.secondarymenu
    at n/a
        in /var/www/foo/vendor/sonata-project/admin-bundle/Admin/Pool.php line 149

    at Sonata\AdminBundle\Admin\Pool->getAdminByClass('Foo\SiteBundle\Entity\Category')
        in /var/www/foo/vendor/sonata-project/admin-bundle/Admin/Admin.php line 1349

    at Sonata\AdminBundle\Admin\Admin->attachAdminClass(object(FieldDescription))
        in /var/www/foo/vendor/sonata-project/doctrine-orm-admin-bundle/Builder/FormContractor.php line 63

    at Sonata\DoctrineORMAdminBundle\Builder\FormContractor->fixFieldDescription(object(MainContent), object(FieldDescription), array('type' => 'entity'))
        in /var/www/foo/vendor/sonata-project/admin-bundle/Form/FormMapper.php line 92

    at Sonata\AdminBundle\Form\FormMapper->add('category', 'entity', array('class' => 'Foo\SiteBundle\Entity\Category', 'property' => 'name', 'admin_code' => 'sonata.domain.site.mainMenu', 'query_builder' => object(Closure)))
        in /var/www/foo/src/Foo/AdminBundle/Domain/Site/MainContent.php line 144

    at Foo\AdminBundle\Domain\Site\MainContent->configureFormFields(object(FormMapper))
        in /var/www/foo/vendor/sonata-project/admin-bundle/Admin/Admin.php line 1298

    at Sonata\AdminBundle\Admin\Admin->defineFormBuilder(object(FormBuilder))
        in /var/www/foo/vendor/sonata-project/admin-bundle/Admin/Admin.php line 1281

    at Sonata\AdminBundle\Admin\Admin->getFormBuilder()
        in /var/www/foo/vendor/sonata-project/admin-bundle/Admin/Admin.php line 907

    at Sonata\AdminBundle\Admin\Admin->buildForm()
        in /var/www/foo/vendor/sonata-project/admin-bundle/Admin/Admin.php line 1381

    at Sonata\AdminBundle\Admin\Admin->getForm()
        in /var/www/foo/vendor/sonata-project/admin-bundle/Controller/CRUDController.php line 518

    at Sonata\AdminBundle\Controller\CRUDController->createAction()
        in  line

    at call_user_func_array(array(object(SortableAdminController), 'createAction'), array())
        in /var/www/foo/app/bootstrap.php.cache line 2953

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in /var/www/foo/app/bootstrap.php.cache line 2915

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in /var/www/foo/app/bootstrap.php.cache line 3064

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Request), '1', true)
        in /var/www/foo/app/bootstrap.php.cache line 2314

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in /var/www/foo/web/app_dev.php line 28
```

Config for the two Admin's:
```
    sonata.domain.site.mainMenu:
        class: Foo\AdminBundle\Domain\Site\Menu\MainMenu
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Main" }
        arguments:
            - ~
            - Foo\SiteBundle\Entity\Category
            - 'PixSortableBehaviorBundle:SortableAdmin'
        calls:
            - [ setTranslationDomain, [CellCareSiteBundle]]
            - [ setContainer, [ @service_container ] ]
            - [ setPositionService, [@pix_sortable_behavior.position]]

    sonata.domain.site.secondaryMenu:
        class: Foo\AdminBundle\Domain\Site\Menu\SecondaryMenu
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Secondary" }
        arguments:
            - ~
            - Foo\SiteBundle\Entity\Category
            - 'PixSortableBehaviorBundle:SortableAdmin'
        calls:
            - [ setTranslationDomain, [CellCareSiteBundle]]
            - [ setContainer, [ @service_container ] ]
            - [ setPositionService, [@pix_sortable_behavior.position]]
```

Relevant part of my Page Admin:

```
              $formMapper->with('Page Details')
                  ->add('name', null, ['label' => 'Name - Used in url'])
                  ->add('displayName', null, ['required' => false, 'label' => 'Name - If different to the above'])
                  ->add('hidden', null, ['required' => false, 'label' => 'Hide from Menu'])
                  ->add('category', 'entity', [
                     'class'         => 'Foo\SiteBundle\Entity\Category',
                     'property'      => 'name',
                     'query_builder' => function (EntityRepository $er) {
                          $qb = $er->createQueryBuilder('cat');
                          $qb
                              ->where('cat.menu = :menu')
                              ->setParameter('menu', 'main')
                          ;

                          return $qb;
                      }
                  ])
              ->end()
```
