### ISSUE TITLE
Translate custom entity in the breadcrumbs

### ISSUE THREAD

**Issue by pclaitte** [sonata-project/SonataAdminBundle#2237]
Hello, 
I can't translate the entity name who is displayed in the SonataAdminBundle breadcrumbs. The entity name is returned by the _toString method of the entity. I have found nothing about that in the documentation.

I have tried to add the translation in messages.fr.yml, MyXXXBundle.fr.yml without success.

You can see my admin.yml below : 

```
services:
    sonata.admin.people:
        class: My\SearchBundle\Admin\PeopleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Peoples", label: "Peoples", label_catalogue: "MySearchBundle" }
        arguments:
            - ~
            - My\SearchBundle\Entity\People
            - ~
        calls:
            - [ setTranslationDomain, [MySearchBundle]]
```

Can you help me ?
Thanks.
