### ISSUE TITLE
Update and Update and Close buttons on my UserAdmin class do nothing when clicked

### ISSUE THREAD

**Issue by Tocacar** [sonata-project/SonataAdminBundle#2284]
In my other Admin forms, these buttons work fine (those I've checked anyway, I have a quite a few and haven't gone through them all).  However, for my UserAdmin class (which is SonataUser extending FOSUser) these buttons do nothing at all when clicked.  The delete button works fine.

This was working fine until I upgraded to the latest version of Sonata and Symfony yesterday.

Service definition:

```
    sonata.admin.user:
        class:  AMS\AdminBundle\Admin\UserAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: ams_institute, label: Users }
        arguments: [null, AMS\UserBundle\Entity\User, SonataAdminBundle:CRUD]
```

composer.json (sf2 and sonata parts only):

```
        "symfony/symfony": "2.5.*",
        "sonata-project/cache-bundle": "2.2.*@dev",
        "sonata-project/block-bundle": "2.2.*",
        "sonata-project/jquery-bundle": "1.8.*@dev",
        "sonata-project/admin-bundle": "2.3.*@dev",
        "sonata-project/exporter": "1.*",
        "sonata-project/doctrine-orm-admin-bundle": "2.2.*",
        "sonata-project/easy-extends-bundle" : "2.1.*@dev",
        "sonata-project/user-bundle": "2.3.*@dev",
        "sonata-project/datagrid-bundle": "2.2.*@dev",
        "sonata-project/core-bundle": "~2.2@dev"
```

Is it just me?
