### ISSUE TITLE
Access Denied on previously working user block when switching role security handler

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2289]
So far I have my dashboard working and after logging in I can edit users and their roles.

My User has the following roles in the database:

``` javascript
a:4:{i:0;s:10:"ROLE_ADMIN";i:1;s:16:"ROLE_SUPER:ADMIN";i:2;s:30:"ROLE_PROJECT_MANAGER";i:3;s:17:"ROLE_SONATA_ADMIN";}
```

I would like to create my own roles e.g. `ROLE_PROJECT_MANAGER`.
Before I add them to my security config I switched to the role security handler:

``` yaml
sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
```

Since then I am getting an `Access Denied` on the User edit mask that I was able to edit before.

My bundle versions:

``` javascript
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.5.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "stof/doctrine-extensions-bundle": "=v1.1.0",
        "gedmo/doctrine-extensions": "=v2.3.9",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0",
        "sensio/framework-extra-bundle": "~3.0",
        "incenteev/composer-parameter-handler": "~2.0",
        "mopa/bootstrap-bundle": "=v2.3.0",
        "twbs/bootstrap": "=v3.2.0",
        "friendsofsymfony/user-bundle": "=v1.3.4",
        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "=2.2.7",
        "sonata-project/block-bundle": "dev-master",
        "sonata-project/cache-bundle": "=2.1.7",
        "sonata-project/core-bundle": "dev-master",
        "sonata-project/user-bundle": "=2.2.4",
        "sonata-project/intl-bundle": "dev-master",
        "sonata-project/easy-extends-bundle": "dev-master",
        "knplabs/knp-menu": "=v1.1.2",
        "lifo/typeahead-bundle": "=1.0",
        "genemu/form-bundle": "=v2.2.2",
        "ivaynberg/select2": "=3.5.0",
        "thrace/datagrid-bundle": "=v1.1.1",
        "knplabs/knp-paginator-bundle": "=2.4.0",
        "apy/datagrid-bundle": "dev-master",
        "guzzlehttp/guzzle": "=4.1.4",
        "wiredmedia/doctrine-extensions": "=v0.1",
        "jms/security-extra-bundle": "dev-master"
    },
```

My `config.yml`:

``` yaml
fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User

    group:
        group_class: Application\Sonata\UserBundle\Entity\Group   
        group_manager: sonata.user.orm.group_manager  

    service:
        user_manager: sonata.user.orm.user_manager         

sonata_user:
    security_acl:             false
    manager_type: orm
    class:
        user:  Application\Sonata\UserBundle\Entity\User
        group: Application\Sonata\UserBundle\Entity\Group  

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account:
        sonata.block.service.text:
        sonata.block.service.rss:

sonata_admin:
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig    
    security:
        handler: sonata.admin.security.handler.role

```

My `security.yml`:

``` yaml
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented

    # set access_strategy to unanimous, else you may have unexpected behaviors
    access_decision_manager:
        strategy: unanimous

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # -> custom firewall for the admin area of the URL
        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
#                login_path:     /login
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
            anonymous:          true

        # -> end custom configuration

        # default login area for standard users

        # This firewall is used to handle the public login area
        # This part is handled by the FOS User Bundle
        main:
            pattern:             .*
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:             true
            anonymous:          true

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

    acl:
        connection: default 

#parameters:
#    # ... other parameters
#    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap        
```

As you can see it is bases on the EasyExtends bundle.
Any idea?

Backlink:
https://groups.google.com/forum/#!topic/sonata-users/O0fA9o0Q4Dk

Possibly related issue:
https://github.com/sonata-project/SonataAdminBundle/issues/2161
