### ISSUE TITLE
Cannot call profile using FOSUserBundle error  route "sonata_user_profile_edit" does not exist

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2307]
I have a working SonataAdminBundle and would like to call the Profile but `http://localhost:8000/profile/` gives me the following error:
**An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "sonata_user_profile_edit" as such route does not exist.") in SonataUserBundle:Profile:action.html.twig at line 27.**

My composer.json:

``` javascript
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.5.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "stof/doctrine-extensions-bundle": "=v1.1.0",
        "gedmo/doctrine-extensions": "=v2.3.9",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0",
        "sensio/framework-extra-bundle": "~3.0",
        "incenteev/composer-parameter-handler": "~2.0",
        "mopa/bootstrap-bundle": "=v2.3.0",
        "twbs/bootstrap": "=v3.2.0",
        "friendsofsymfony/user-bundle": "~1.3",
        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "dev-master",
        "sonata-project/block-bundle": "dev-master",
        "sonata-project/cache-bundle": "dev-master",
        "sonata-project/core-bundle": "dev-master",
        "sonata-project/user-bundle": "=2.2.4",
        "sonata-project/intl-bundle": "dev-master",
        "sonata-project/easy-extends-bundle": "dev-master",
        "knplabs/knp-menu": "=v1.1.2",
        "lifo/typeahead-bundle": "=1.0",
        "genemu/form-bundle": "=v2.2.2",
        "ivaynberg/select2": "=3.5.0",
        "thrace/datagrid-bundle": "=v1.1.1",
        "knplabs/knp-paginator-bundle": "=2.4.0",
        "apy/datagrid-bundle": "dev-master",
        "guzzlehttp/guzzle": "=4.1.4",
        "wiredmedia/doctrine-extensions": "=v0.1",
        "jms/security-extra-bundle": "dev-master"
    },
```

my config.yml:

``` yaml
fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User

    group:
        group_class: Application\Sonata\UserBundle\Entity\Group   
        group_manager: sonata.user.orm.group_manager  

    profile:
        # Authentication Form
        form:
            type:               fos_user_profile
            handler:            fos_user.profile.form.handler.default
            name:               fos_user_profile_form
            validation_groups:  [Authentication] # Please note : this is not the default value

    service:
        user_manager: sonata.user.orm.user_manager         

sonata_user:
    security_acl:             false
    manager_type: orm
    admin:
        user:
          class:      Application\Sonata\UserBundle\Admin\UserAdmin    
    class:
        user:  Application\Sonata\UserBundle\Entity\User
        group: Application\Sonata\UserBundle\Entity\Group  

    profile:
        # Customize user portal menu by setting links
        menu:
            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit_authentication', label: 'link_edit_authentication', domain: 'SonataUserBundle'}

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin_doctrine_orm.block.audit:
            contexts:   [admin]

        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account:
        sonata.block.service.text:
        sonata.block.service.rss:
```

My routing.yml:

``` yaml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
```

When I switch to:

``` yaml
sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile
```

I can see the custom template from `SonataUserBundle:Profile:show.html.twig`.
