### ISSUE TITLE
[Feature request]Adding stylesheets / javascripts to the default ones

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataAdminBundle#2425]
Adding a custom stylesheet on all pages is a bit cumbersome : you have to copy paste an excerpt of the output of `app/console config:dump-reference SonataAdminBundle` into your `config.yml`. It would be nice to have an `extra_stylesheets` and an `extra_javascripts` option that, when used, would add to the default stylesheets / javascripts instead of replacing them. What do you think ?

**Comment by webdevilopers** [comment]
:+1: 

Maybe there is an optional placeholder that can be used to include the parent assets e.g. in twig:
```twig
{% block javascripts %}    
    {{ parent() }}
{% endblock %}
```

for the config something like (but with valid YAML):
```yaml
sonata_admin:
    assets:
        javascripts:
            ~
            - /bundles/sonatacore/vendor/moment/locale/de.js
```
