### ISSUE TITLE
Unable to use the sonata_type_admin field - Field not linked to an admin

### ISSUE THREAD

**Issue by aguidis** [sonata-project/SonataAdminBundle#2585]
I have an entity "Author" and "Image" with a simple OneToOne relation.
I tried to embed an Admin class in my Author admin class for the "image" field which is linked to the Image entity. 

The mapping betweens the two classes is correct. 

I created an Admin class for each entity :

- ImageAdmin works correctly. When I add a new image, the database is updated and the image is uploaded.

- Then I create the AuthorAdmin thanks to the documentation (http://sonata-project.org/bundles/admin/master/doc/reference/form_types.html#sonata-type-admin). But I always have this message : 

> The current field `image` is not linked to an admin. Please create one for the target entity : ``

The admin services are registred in the admin.yml (I used http://sonata-project.org/bundles/admin/master/doc/reference/form_types.html#sonata-type-admin) :

```yml
services:
    sonata.admin.author:
        class: Project\BackendBundle\Admin\AuthorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Author" }
        arguments:
            - ~
            - Project\BackendBundle\Entity\Author
            - ~

    sonata.admin.image:
        class: Project\BackendBundle\Admin\ImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Image" }
        arguments:
            - ~
            - Project\BackendBundle\Entity\Image
            - 'SonataAdminBundle:CRUD'
```

I followed all the documentation but now I don't see the problem. I even try to pass the FieldDescription option "admin_code" :

```php
$formMapper
    ->add('name', 'text', array('label' => 'Author name'))
    ->add(
        'image',
        'sonata_type_admin',
        array(),
        array('admin_code' => 'sonata.admin.image')
    )
;
```
I use the lastest version of sonata admin bundle sonata-project/admin-bundle.

**Comment by j-ledoux** [comment]
Hey guys,

I'd like to reopen this issue as it is happening with the latest stable version of Sonata, without @ORM\Column annotation.
I currently have following version for my project :
* sonata-project/admin-bundle 3.4.0
* sonata-project/block-bundle 3.1.1
* sonata-project/core-bundle 3.0.3
* doctrine/orm 2.5.4
* symfony/symfony 3.0.8

I have the same error message when I try to use sonata_type_admin with all my admin forms.

Here is an example : I 'm trying to include a Company admin form in a Contact

Here are my 2 entities relations parts :
``` php
/**
 * Contact
 *
 * @ORM\Table(name="contact")
 * @ORM\Entity
 */
class Contact
{
    /**
     * @ORM\ManyToOne(targetEntity="Project\UserBundle\Entity\Company", inversedBy="contacts")
     * @ORM\JoinColumn(name="company_id", referencedColumnName="id")
     * @Assert\NotNull
     */
    protected $company;
}
```
``` php
/**
 * Company
 *
 * @ORM\Table(name="company")
 * @ORM\Entity
 */
class Company
{
    /**
     * @ORM\OneToMany(targetEntity="Project\UserBundle\Entity\Contact", mappedBy="company")
     */
    protected $contacts;
}
```

Services :

``` yaml
    project_user.admin.company:
        class: Project\UserBundle\Admin\CompanyAdmin
        arguments: [~, Project\UserBundle\Entity\Company, 'SonataAdminBundle:CRUD']
        tags:
            - {name: sonata.admin, manager_type: orm, label: Company}
        calls:
            - [ setTranslationDomain, ['ProjectModelAdmin']]

    project_user.admin.contact:
        class: Project\UserBundle\Admin\ContactAdmin
        arguments: [~, Project\UserBundle\Entity\Contact, ProjectUserBundle:ContactAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Contact}
        calls:
            - [ setTranslationDomain, ['ProjectModelAdmin']]
```

In ContactAdmin class :

``` php
$formMapper
    ->add('company', 'sonata_type_admin',
        array(
            'required'   => true,
            'btn_add'    => false,
            'btn_delete' => false,
        ),
        array(
            'admin_code' => 'project_user.admin.company',
        )
    )
;
```

Both admin class works well separately, but with company as a sonata_type_admin (as well as my other admin classes) It shows up the following error message :

> The current field `company` is not linked to an admin. Please create one for the target entity : ``
