### ISSUE TITLE
Translation of menu items in add block should use a different label then the admin label

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2618]
My admin has an overview-focussed label `Contracts Overview`:

``` yaml
services:
    sonata.admin.contract:
        class: Plusquam\Bundle\ContractBundle\Admin\ContractAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contracts", label_catalogue: "messages", label: "Contracts Overview" }
```

This class is added to a dashboard group named `Contracts`:

``` yaml
sonata_admin:
    dashboard:
        groups:    
            contracts:
                label: "Contracts"
                items:
                    - sonata.admin.contract
                roles: [ ROLE_PROJECT_MANAGER ]
```

When clicking on the `add_block` I get the following label combination:
**+** -> **Contracts** -> **Contracts Overview**

My customer finds this misleading since they expect **+** -> **Contracts** -> **(New) Contract** or **(Add) Contract**.

The `add_block` simply uses the admin label:
https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/Core/add_block.html.twig#L48

while buttons for instance use the `link_action_create`:
https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/Button/create_button.html.twig#L23
- Can we improve the labels here?
- Is there a way to configure individual labels or creation links - without overwriting the templates?
- Maybethe `configureRoutes` method of the admin class can be involved?
