### ISSUE TITLE
Checkbox labels NOT showing with Bootstrap SF2.6 form theme

### ISSUE THREAD

**Issue by davidromani** [sonata-project/SonataAdminBundle#2630]
Hello.

I enable this config with SF2.6 and Sonata Admin 2.3, then checkbox labels are not showing in forms.

```yaml
# app/config.yml
twig:
    form:
        resources:
            - "bootstrap_3_layout.html.twig"
```

**Comment by Axinet** [comment]
I encountered the same problem today. 

It looks like the problem is 2-step:
1) block "checkbox_row" from "bootstrap_3_layout.html.twig" takes precedence over block "form_row" from "form_admin_fields.html.twig"
2) block "checkbox_label" from "bootstrap_3_layout.html.twig" takes precedence over block "form_label" from "form_admin_fields.html.twig"

To solve this problem I used additional/custom templates for sonata admin forms by adding to config:
````yml
sonata_doctrine_orm_admin:
    templates:
        form:
            - AppBundle:Admin:my_form_admin_fields.html.twig
````

and overridden problematic templates (appeding them to "form_admin_fields.html.twig" from sonata admin bundle whould be a possible work around for this problem, but maybe there are some better ones?)

````yml
{% extends 'SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig' %}

{% block checkbox_row -%}
    {{ block('form_row') }}
{%- endblock checkbox_row %}

{% block checkbox_label %}
    {{ block('form_label') }}
{% endblock checkbox_label %}
````
