### ISSUE TITLE
datepicker format

### ISSUE THREAD

**Issue by greg606** [sonata-project/SonataAdminBundle#2675]
I am unable to set datepicker format.
I set it in admin class like this:
->add('opening', 'sonata_type_date_picker', ['required' => false, 'format'=>'yyyy-MM-dd'])
but it's not working any idea why?

**Comment by afurculita** [comment]
@greg606 do you get any errors?

**Comment by pulzarraider** [comment]
Maybe you have forgot to add `SonataCoreBundle:Form:datepicker.html.twig` in the twig form resources in app/config.yml:

```yml
twig:
    # ...
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'
```
