### ISSUE TITLE
Warning: Illegal string offset 'admin'

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataAdminBundle#2732]
Just checkout to latest 2.4.x-dev version of sonata-admin-bundle and got this error:

```
An exception has been thrown during the rendering of a template ("Warning: Illegal string offset 'admin'") in SonataAdminBundle:Core:dashboard.html.twig at line 88.
```

Here, my sonata configuration file. As you can see, I deactivate all the overrides without any success.

```yaml
# SonataBlock Configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]

# SonataAdmin Configuration
sonata_admin:
    title: Administration
#    templates:
#        layout:               admin/standard_layout.html.twig
#        user_block:           admin/CORE/user_block.html.twig
#        search_result_block:  admin/Block/block_search_result.html.twig

#sonata_doctrine_orm_admin:
#    templates:
#        types:
#            list:
#                user:       admin/CRUD/list_user.html.twig
#                partner:    admin/CRUD/list_partner.html.twig
#                raw:        admin/CRUD/list_raw.html.twig
#            show:
#                user:       admin/CRUD/show_user.html.twig
#                partner:    admin/CRUD/show_partner.html.twig
#                raw:        admin/CRUD/show_raw.html.twig
```

Installed sonata's packages:

```bash
$ composer -i info | grep sonata
sonata-project/admin-bundle              dev-ddn 28597e8                   Symfony SonataAdminBundle
sonata-project/block-bundle              2.2.13                            Symfony SonataBlockBundle
sonata-project/cache                     1.0.4                             Cache library
sonata-project/core-bundle               dev-master 87a84ae                Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle dev-list-builder-template 08c7715 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.9                             Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.3.4                             Lightweight Exporter library
sonata-project/intl-bundle               2.2.1                             Symfony SonataIntlBundle
```
Note: `dev-ddn` branch was just synchronized from your master branch as you can see [here](https://github.com/Soullivaneuh/SonataAdminBundle/commits/ddn).

Please tell me if you need more information to solve this issue.

Thanks.
