### ISSUE TITLE
Isotope lib for edit entity page

### ISSUE THREAD

**Issue by zhil** [sonata-project/SonataAdminBundle#2994]
When we have a lot of groups in configureFormFields with "class"=>'col-md-6' (so, they will be alligned in 2 collumns on wide screens) - they aligned with big "blank spaces".

I have altered [demo site code](http://demo.sonata-project.org/admin/app/site/2/edit) to show it - 
![image](https://cloud.githubusercontent.com/assets/981783/7686071/dcb7f83e-fd9b-11e4-9d6a-842edacf1c89.png)

It can be fixed with this library http://isotope.metafizzy.co/layout-modes/masonry.html
@rande will you accept PR with ability to enable this lib on edit page?

**Comment by rccc** [comment]
Hello,

 The licence of isotope says : "If you want to use Isotope to develop commercial sites, themes, projects, and applications, the commercial license is the appropriate license." . So it may not be a good solutoin solution for all sonata users.

You may consider using class"=>'col-md-12', and add your own javascript lib ( isotope or masonry ) and you own css for the box in a custom edit template.

++

**Comment by zhil** [comment]
@rccc well, what about adding easy way to use isotope in core system + docs into documentaion?
Something like
```
If you want to use isotope - you need to set such a parameters in config.yml
sonata:
   isotope:
       lib: /bundles/somebundle/isotope.js
       enabled: true
```
Its really "must have" as for me, what do you think?

By the way, licence for isotope is [$25 per single developer](http://isotope.metafizzy.co/#license) - pretty affordable.
