### ISSUE TITLE
Wrong block class from config

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataAdminBundle#3241]
If I set the following configuration:

``` yaml
    dashboard:
        blocks:
            -
                position: top
                class: col-md-12
                type: block.admin.quick_info
            -
                position: left
                class: col-lg-6
                type: block.admin.support_info
```

The block `block.admin.support_info` get a col-**md**-6 class, not **lg**.

**Comment by jordisala1991** [comment]
Just tried with this:

```
        blocks:
            -
                position: top
                class: col-md-12
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Welcome to the Sonata Admin</h2>
            -
                position: top
                class: col-lg-6
                type: sonata.block.service.text
                settings:
                    content: >
                        Test
```

And it adds the correct classes on each block.

Closing for now, probably related to cache/config/old sonata version. If you still having this issue, please reopen and provide more information about the problem.
