### ISSUE TITLE
CRITICAL Login no longer working - Unable to generate a URL

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3307]
I recently had to update production to `dev-master`. When clicking the login URL I get:
request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "sonata_user_admin_resetting_request" as such route does not exist.") in "SonataUserBundle:Admin/Security:login.html.twig" at line 60."

Have the routes changed?

The only way to login now is this link:
http://example.com/login

Before I could use:
http://example.com/admin/dashboard

**Comment by Soullivaneuh** [comment]
@rande If this is a BC issue, commit should be reverted.

@OskarStark I think you manage a PR with route definitions, isn't it?

**Comment by webdevilopers** [comment]
Maybe this is related to a `SonataUser` issue otherwise?

I replaced
```twig
{{ url('sonata_admin_dashboard') }}
```
with
```twig
{{ path('sonata_user_admin_security_login') }}
```
for now.

I'm still checking if my config causes this.

**Comment by sagikazarmark** [comment]
Yes, the routing must be changed.

Check here: https://github.com/sonata-project/sandbox/blob/2.4-develop/app/config/routing_admin.yml#L12

Make sure to add the `qis` prefix.

**Comment by sagikazarmark** [comment]
@Soullivaneuh I already added this to the docs. How often do you build the documentation?

**Comment by sagikazarmark** [comment]
Actually, the right documentation for this problem should be here: https://sonata-project.org/bundles/user/master/doc/reference/installation.html#integrating-the-bundle-into-the-sonata-admin-bundle

@Soullivaneuh yes, this is some sort of BC issue, but I am not sure path generation can be implemented in a BC preserving way. Probably it should be mentioned in the upgrade guide.

**Comment by webdevilopers** [comment]
Thanks @sagikazarmark, the new config works fine. The `qis` prefix was my custom route, no problem there.

Thanks for the quick response! :+1:

**Comment by sagikazarmark** [comment]
@webdevilopers I know it is your custom prefix, but as I can see you replaced admin with that custom prefix. The full path to the admin resetting would be `/admin/resetting`, which in case would be `/qis/resetting`, wouldn't it?

Glad I could help!

**Comment by sagikazarmark** [comment]
Also, note that in the file I linked `sonata_user` route is renamed to `sonata_user_admin_security`. It is not used anywhere in the project, I am just pointing to make sure no confusion will be. :wink:

**Comment by webdevilopers** [comment]
My current config seems to work fine:
```yaml
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /qis
```

The "Forgotten password" leads to `/resetting/request` without `qis`.

Since it is based on `fos_user` it is good to have no `admin` relation inside that route / path.

**Comment by sagikazarmark** [comment]
> My current config seems to work fine

It is completely fine. Just pointed that the name changed in the configuration and the sandbox.

> Since it is based on `fos_user` it is good to have no `admin` relation inside that route / path.

No, it is not good. The PR which caused the issue for you implemented separate password resetting for the admin panel. This is especially good if you don't have user support on the frontend.

Also, I am not sure the separate routing configurations will not collide if you don't use them as intended. Currently both routes (admin resetting, frontend resetting) points to the same path, which is not good IMO.

**Comment by webdevilopers** [comment]
Can you link the PR? Thanks!

**Comment by sagikazarmark** [comment]
Discussion: sonata-project/SonataUserBundle#618

sonata-project/SonataUserBundle#620

**Comment by Soullivaneuh** [comment]
> Yes, the routing must be changed.

This **should not**. This is completly BC break as you can see. BC break things like route name change should be done on major version.

That PR must be reverted to be reworked. cc @OskarStark @rande.

**Comment by sagikazarmark** [comment]
No need to revert, I will try to fix it.

**Comment by rande** [comment]
@sagikazarmark see related comment in your UserBundle PR.

**Comment by sagikazarmark** [comment]
Pushed a fix

**Comment by webdevilopers** [comment]
Do I have to revert the changes suggestend by @sagikazarmark then?
With the PR merged and updating to current `dev-master` everything should work as before with my old config?

**Comment by sagikazarmark** [comment]
Yes, it should, but it's a deprecated way, you should use the new configuration.

**Comment by tophsic** [comment]
Many thx, I just updated to get the BC before you merged :wink: So I lost... 10 min :+1:

**Comment by sagikazarmark** [comment]
:wink:

**Comment by webdevilopers** [comment]
Which attempt is correct when *2.4* will be released?

**Comment by Soullivaneuh** [comment]
> Which attempt is correct when 2.4 will be released?

@webdevilopers The new one. As @sagikazarmark says, the old route works again but is deprecated. You will receive warnings with it.

**Comment by sagikazarmark** [comment]
The actual BC break will be introduced in 3.0, until then the old config is just deprecated. Actually not having the new routes in your config is.

**Comment by sagikazarmark** [comment]
@Soullivaneuh isn't it 2.3? :wink:

**Comment by Soullivaneuh** [comment]
@sagikazarmark It is, for user-bundle. Here, we are in admin-bundle. See the tags! :-)

**Comment by sagikazarmark** [comment]
Oh, crap, I missed the repo change.

**Comment by webdevilopers** [comment]
Ok, because using the new routes I get this when trying to send a new password:
```
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "fos_user_resetting_reset" as such route does not exist."
```

Any more routes to update?

**Comment by sagikazarmark** [comment]
What is your current config?

**Comment by webdevilopers** [comment]
```yaml
#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /qis

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /qis

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /qis

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile
```

**Comment by sagikazarmark** [comment]
Try prefixing `sonata_user_admin_security` and `sonata_user_admin_resetting` prefixing with `/qis`. Also, `sonata_user` is not needed anymore.

**Comment by webdevilopers** [comment]
Using
```yaml
sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /qis/resetting
```

Redirects me to the login page. Which is the same page where I came from clicking "forgotten password".
Because the link / route is behind the `qis` aka `admin` firewall it wants me to login in order to send my a forgotten password! ;)
