### ISSUE TITLE
form action is `update` instead `create`

### ISSUE THREAD

**Issue by dvapelnik** [sonata-project/SonataAdminBundle#3330]
Form action is `update` instead `create` when part of composite primary key is defined.
I'm using `Post` entity with composite primary key: (`id` and `context`)

``` yaml
AppBundle\Entity\Post:
    type: entity
    table: null
    id:
        id:
            type: integer
        context:
            associationKey: true
    manyToOne:
        context:
            targetEntity: Application\Sonata\ClassificationBundle\Entity\Context
```

I override `Admin::getNewInstance` method with next code

``` php
public function getNewInstance()
{
    /** @var Post $newInstance */
    $newInstance = parent::getNewInstance();
    $newInstance->setContext($this->getContext());

    return $newInstance;
}
```

``` php

/**
 * @return null|Context
 * @throws \Exception
 */
protected function getContext()
{
    if (null === $this->contextId) {
        throw new \Exception("'contextId' net defined");
    }
    $context = $this->getConfigurationPool()->getContainer()
        ->get('doctrine')->getEntityManager()
        ->find('ApplicationSonataClassificationBundle:Context', $this->contextId
    if (!$context) {
        throw new \Exception("Context with id '{$this->contextId}' not found");
    }
    return $context;
}
```

After this I see action attribute on rendered page as **edit** `/admin/post/articles/articles/edit?uniqid=...` instead **create**.

I'm using hidden field `contextId` with `prePersist` listener for converting string `contextId` to `context` entity as workaround of this problem but I want to find more clearly solution then my workaround.

I think that this is correct but unexpected behavior of admin.
