### ISSUE TITLE
Using sonata_type_model_autocomplete throws exception

### ISSUE THREAD

**Issue by ElectricMaxxx** [sonata-project/SonataAdminBundle#3341]
We are trying to use `sonata_type_model_autocomplete` for the first time and are getting the follwoing Exception:

```
Catchable Fatal Error: Argument 1 passed to Sonata\AdminBundle\Form\DataTransformer\ModelToIdPropertyTransformer::__construct() must implement interface Sonata\AdminBundle\Model\ModelManagerInterface, null given, called in /path-to-vendo/vendor/sonata-project/admin-bundle/Form/Type/ModelAutocompleteType.php on line 35 and defined in /path-to-vendor/vendor/sonata-project/admin-bundle/Form/DataTransformer/ModelToIdPropertyTransformer.php line 42
```

The form builder is getting this add:

``` php
            ->add(
                'user',
                'sonata_type_model_autocomplete',
                [
                    'property' => 'username'
                ],
                [
                    'type_options' =>
                        ['delete' => false]
                ]
            )
``` 

The admin defintion looks like:

``` yaml
  md.admin.admin.customer:
    class: %md.admin.admin.customer.class%
    arguments:
      - ~
      - My\ApplicationBundle\Entity\Customer
      - ~
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Customer / Customer Company", label: "Customer" }
```

What am a i doing wrong? We are using the orm version.
