### ISSUE TITLE
[Feature] Add GraphBlockService

### ISSUE THREAD

**Issue by tashanta** [sonata-project/SonataAdminBundle#3377]
I would like to make a PR to provide a new block service in dashboard : GraphBlockService.
This block is able to generate some kind of graphs with Graph Js libray (http://www.chartjs.org/).

![graph](https://cloud.githubusercontent.com/assets/5037520/10600814/8f88b53a-770d-11e5-8943-8ac6e8e9f9d3.png)

This Block service permits to define what kind of graph you want, and what data to consolidate on your dashboard with very simple configuration :

```yaml
    # app/config/config.yml
    dashboard:
        blocks:
          -
            position: left
            type: foo.block.service.graph_report
            settings:
                chart_id: customers_by_product
                title: Adhérents par année
                graph_type: donut
                sql: >
                    SELECT 
                        product
                        ,COUNT(DISTINCT customers) as pop
                    FROM Foo\AdminBundle\Entity\Product product
                    LEFT JOIN product.orderElements allOrderElements
                    LEFT JOIN allOrderElements.order allOrders
                    LEFT JOIN allOrders.customer customers
                    GROUP BY product.id
                mapping:
                    label: "[0][name]"
                    value: "[pop]"

  ...
```

Where is the best place for this PR ? AdminBundle (i planned to rename ``sql`` parameter in something else for ODM) ? Is it possible to add charjs to bower ?
