### ISSUE TITLE
Unable to generate a URL for     the named route "admin_sonata_user_user_create"

### ISSUE THREAD

**Issue by AntonioCS** [sonata-project/SonataAdminBundle#3412]
So I was trying to got to the admin page (sonata admin bundle) and I was getting this:

> An exception has been thrown during the rendering of a template ("Unable to generate a URL for
>     the named route "admin_sonata_user_user_create" as such route does not exist.") in 
>     SonataAdminBundle:Block:block_admin_list.html.twig at line 38.

The only way to fix this was to add this to the routing.yml:

```
_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin
```

But where is this in the documentation????
