### ISSUE TITLE
Error trying to customize form rendering

### ISSUE THREAD

**Issue by beni0888** [sonata-project/SonataAdminBundle#3426]
I'm experiencing an error trying to customize the rendering of a single form field. I'm following the instuctions of http://symfony.com/doc/2.3/cookbook/form/form_customization.html#method-1-inside-the-same-template-as-the-form but I get the following error:

> Variable "base_template" does not exist in SonataAdminBundle:CRUD:base_edit.html.twig at line 12 

My code is quite simple until now, I have a custom edit template and I am trying to implemente the field rendering customization in it. It is as follows:

I tell the admin to use a custom edit template:

``` yaml
# .../app/config/sonata.yml
microsite-ad,om:
        class: MyCompany\AdminBundle\Admin\MicrositeAdmin
        arguments: [~, MyCompany\ApplicationBundle\Entity\Microsite, AdminBundle:MicrositeCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Microsites"
              group: "Microsites"
        calls:
            - [ setTranslationDomain, [AdminBundle]]
            - [ setTemplate, [edit, AdminBundle:Admin:microsite_edit.html.twig] ]
```

And in the custom template:

``` twig
{# .../src/MyCompany/Resources/views/Admin/microsite_edit.html.twig #}
{% extends 'SonataAdminBundle:CRUD:base_edit.html.twig' %}

{% form_theme form _self %}
```

As soon as I add the line {% form_theme form _self %} to the template, I get the error. I've tried to put the instruction inside the form block but it does not run either. 

I don't know if I'm doing something bad or if what I want to do is not possible.

Thanks for your help.
