### ISSUE TITLE
Autoactive cusrom item on navbar

### ISSUE THREAD

**Issue by muspelheim** [sonata-project/SonataAdminBundle#3471]
look comments on config
```yml
sonata_admin:
    dashboard:
        groups:
            sonata.admin.group.content:
                label:           core.menu.routing
                label_catalogue: CoreBundle
                icon:            '<i class="fa fa-puzzle-piece"></i>'
                items:
                    - route:        application_session //if I pick this custom link on navbar, element not have class active
                      label:        'Session'
                    - application.admin.provider //all good, if i pick this item on meny, he highlighted and have active class
```
