### ISSUE TITLE
Not sticky navigation bar on mobile

### ISSUE THREAD

**Issue by peter-gribanov** [sonata-project/SonataAdminBundle#3570]
Portrait screen orientation

![Portrait screen orientation](https://cloud.githubusercontent.com/assets/1954436/12746288/ead01642-c9ae-11e5-9873-961ea8f7acc3.png)

After scroll bottom

![Portrait screen orientation after scroll bottom](https://cloud.githubusercontent.com/assets/1954436/12746286/eacad01a-c9ae-11e5-9d3f-65da9e233a78.png)

Landscape screen orientation

![landscape screen orientation](https://cloud.githubusercontent.com/assets/1954436/12746287/eacc6c54-c9ae-11e5-807a-37e489db322d.png)

After scroll bottom

![landscape screen orientation after scroll bottom](https://cloud.githubusercontent.com/assets/1954436/12746289/ead0e202-c9ae-11e5-9c32-2b163280ae94.png)

The navigation bar hides most of the screen. This problem must be solved not in my project. It needs to be solved in SonataAdminBundle.

**Comment by peter-gribanov** [comment]
screenshots from Sony Xperia Z2

**Comment by core23** [comment]
IMO this is hard to fix, because there are to many different screen resolutions on mobile devices

**Comment by peter-gribanov** [comment]
For screens width less than [767px](https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/public/vendor/admin-lte/dist/css/AdminLTE.css#L72) can be turned off sticky navigation bar.

**Comment by peter-gribanov** [comment]
Example solution for my project
```css

@media (max-width: 767px) {
  body.fixed .main-header {
    position: relative;
  }
  body.fixed .content-wrapper,
  body.fixed .right-side {
    padding-top: 0;
  }
  body.fixed .content-header .navbar.stuck {
    top: 0;
    position: relative;
    margin: 0;
    width: 100% !important;
  }
  body.fixed .main-sidebar {
    position: absolute;
  }
  /* disable slimScroll */
  body.fixed .main-sidebar .slimScrollDiv,
  body.fixed .main-sidebar .sidebar {
    overflow: visible !important;
    height: auto !important;
  }
  .navbar-custom-menu > .navbar-nav > li > .dropdown-menu {
    width: auto !important;
    min-width: 230px; /* width of the left sidebar */
  }
}
```
