### ISSUE TITLE
Impossible use dropdown menu on mobile

### ISSUE THREAD

**Issue by peter-gribanov** [sonata-project/SonataAdminBundle#3576]
Impossible use dropdown menu on mobile, in portrait screen orientation

![screen](https://cloud.githubusercontent.com/assets/1954436/12850587/88d13bf8-cc36-11e5-8c9f-71c907ce9377.png)

Example solution

``` css
@media (max-width: 767px) {
  .navbar-custom-menu > .navbar-nav > li >.dropdown-menu {
    width: auto !important;
    min-width: 230px; /* width of the left sidebar */
  }
}
```
