### ISSUE TITLE
Uploading image through richhtml fails

### ISSUE THREAD

**Issue by bilougit** [sonata-project/SonataAdminBundle#3716]
I try to add some content in a block through richhtml but I get this error when I try to load image from the server
`Method "hasDisplayableFilters" for object "Sonata\AdminBundle\Datagrid\Datagrid" does not exist in SonataFormatterBundle:Ckeditor:browser.html.twig at line 252`

config.yml

``` YAML
ivory_ck_editor:
    default_config: default
    configs:
        default:
            toolbar: full
            # default toolbar plus Format button
            filebrowserBrowseRoute: admin_sonata_media_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_sonata_media_media_ckeditor_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
```

To overcome this, I override `browser.html.twig` and replace the line that raises the error with a static value, and this time I get this 

```
Key "show_filter" for array with keys "format, field_name, route, placeholder, link_parameters, field_type, field_options, options, parent_association_mappings, field_mapping, global_search, code, name, label" does not exist in SonataFormatterBundle:Ckeditor:browser.html.twig at line 261
```

Same thing, I edited the line considering all tests on show_filter as false. This time I didn't get an error however I didn't get the filter, which I need because the server is gonna have thousands of images soon.

I assume that modifications I made aren't good:

``` html
<!-- line 252 -->
<div class="col-xs-12 col-md-12 sonata-filters-box" style="display: none" id="filter-container-{{ admin.uniqid() }}">
.....
<!-- line 262 -->
<div class="form-group" id="filter-{{ admin.uniqid }}-{{ filter.name }}" sonata-filter="{{ 'false' }}" style="display: {% if (filter.isActive()) %}block{% else %}none{% endif %}">
```

```
sonata-project/admin-bundle              2.3.10             Symfony SonataAdminBundle
sonata-project/block-bundle              2.2.13             Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/cache-bundle              2.2.5              This bundle provides caching services
sonata-project/classification-bundle     2.2.x-dev fe3edca  Symfony SonataClassificationBundle
sonata-project/core-bundle               2.3.10             Symfony SonataCoreBundle
sonata-project/datagrid-bundle           dev-master 6e7940a Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 2.3.3              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10             Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.4.1              Lightweight Exporter library
sonata-project/formatter-bundle          dev-master d0ab65b Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2              Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.2.4              Symfony SonataIntlBundle
sonata-project/media-bundle              2.3.3              Symfony SonataMediaBundle
sonata-project/news-bundle               2.3.5              Symfony SonataNewsBundle
sonata-project/notification-bundle       2.3.3              Symfony SonataNotificationBundle
sonata-project/page-bundle               2.3.9              Symfony SonataPageBundle
sonata-project/seo-bundle                1.1.10             Symfony SonataSeoBundle
sonata-project/user-bundle               2.2.4              Symfony SonataUserBundle
```
