### ISSUE TITLE
unique constraint with editable => true

### ISSUE THREAD

**Issue by metaer** [sonata-project/SonataAdminBundle#3717]
When I try to set unique field value to another entity in form, it works ok:
screenshot http://dl2.joxi.net/drive/2016/04/12/0004/2633/289353/53/56376a55c2.jpg

But when I try to edit value in field list, it throws exception and I get 500 error:

> Uncaught PHP Exception Sonata\AdminBundle\Exception\ModelManagerException: "Failed to update object: Evaluation\CabinetBundle\Entity\RealExpert" at /home/user/PhpstormProjects/myProject/vendor/sonata-project/doctrine-orm-admin-bundle/Model/ModelManager.php line 158
> 
> "previous": {
>         "class": "Doctrine\DBAL\DBALException",
>         "message": "An exception occurred while executing 'UPDATE RealExpert SET login = ? WHERE id = ?' with params [\"jjj\", 2]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'jjj' for key 'UNIQ_E1BD4B8BAA08CB10'",

edit in list screenshot: http://joxi.ru/krDpRMOu0o0k7r.jpg

other validations (length for example) work good with editable => true and in form edit

my validation.yml:

``` yaml
Evaluation\CabinetBundle\Entity\RealExpert:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: login
            message: 'Такой логин р. эксперта уже заведен'
    properties:
        login:
            - Length:
                min: 1
                max: 100
                minMessage: Логин эксперта должен содержать от 1 до 100 символов
                maxMessage: Логин эксперта должен содержать от 1 до 100 символов
```
