### ISSUE TITLE
Key "template" does not exist when merging _action options

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataAdminBundle#3828]
Error on 3.x.

To reproduce, setup this tiny `AdminExtension` class:

``` php
final class ListActionsAdminExtension extends AdminExtension
{
    public function configureListFields(ListMapper $listMapper)
    {
        $options = [
            'actions' => [
                'show' => [],
                'edit' => [],
                'delete' => [],
            ],
        ];

        if ($listMapper->has('_action')) {
            $listMapper->get('_action')->mergeOptions($options);
        } else {
            $listMapper->add('_action', null, $options);
        }
    }
}
```

This class will merge default actions to defined actions if defined, adding them if not.

And this admin class:

``` php
class ApiKeyAdmin extends Admin
{
    protected function configureListFields(ListMapper $list)
    {
        $list
            ->add('name')
            ->add('_action', 'actions', [
                'actions'   => [
                    'reset'     => ['template' => 'admin/api_key/list__action_reset.html.twig'],
                ],
            ])
        ;
    }
}
```

And them define the services:

``` yaml
services:
    admin.extension.list_actions:
        class: AppBundle\Admin\Extension\ListActionsAdminExtension
        tags:
            - { name: sonata.admin.extension, global: true }
    admin.api_key:
        class: AppBundle\Admin\ApiKeyAdmin
        arguments: [ ~, AppBundle\Entity\ApiKey, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: API Auth, label: Api Key }
```

Finally, go to your api keys list. You will get this error:

```
Key "template" does not exist as the array is empty in SonataAdminBundle:CRUD:list__action.html.twig at line 17
```

It seems internal default template are auto-filled when adding the `_action`, but is lost if you merge your options.
