### ISSUE TITLE
Suggestion: Shouldn't subBundle templates extend to configured Sonata Admin templates?

### ISSUE THREAD

**Issue by codebach** [sonata-project/SonataAdminBundle#3875]
In Sonata Admin we can configure the CrudController Action Templates.

``` yaml
list : SonataAdminBundle:CRUD:list.html.twig
show : SonataAdminBundle:CRUD:show.html.twig
edit : SonataAdminBundle:CRUD:edit.html.twig
history : SonataAdminBundle:CRUD:history.html.twig
preview : SonataAdminBundle:CRUD:preview.html.twig
delete : SonataAdminBundle:CRUD:delete.html.twig
batch_confirmation : SonataAdminBundle:CRUD:batch_confirmation.html.twig
acl : SonataAdminBundle:CRUD:acl.html.twig
```

But all the other bundle templates are still being extended the base templates. 

For example, SonataMediaBundle/Resources/MediaAdmin/edit.html.twig is being extended to this:

``` twig
{% extends 'SonataAdminBundle:CRUD:base_edit.html.twig' %}
```

This template should be extended to the template that we configured:

As I checked that all the subBundles of Sonata templates are being extend to base action templates. I suggest that we sould change them to extend to the configured templates.

As an example:

``` yaml
sonata_admin:
    templates:
        edit : SonataAdminBundle:CRUD:overwritten_edit.html.twig
```

So in SonataMediaBundle/Resources/MediaAdmin/edit.html.twig

``` twig
{% extends sonata_admin.templates.edit %}
```

We can global the param in twig or an extension can help to get the param or any other suggestion could be to get the parameter in twig.
