### ISSUE TITLE
The CSRF token is invalid

### ISSUE THREAD

**Issue by gusdecool** [sonata-project/SonataAdminBundle#3902]
| Question | Answer |
| --- | --- |
| Bundle version | sonata-project/admin-bundle 3.1.0 |
| Symfony version | symfony/symfony v3.1.0 |
| php version | PHP 5.6.20-3+donate.sury.org~trusty+1 |
# Error message

```
The CSRF token is invalid. Please try to resubmit the form.
```
# Steps to reproduce
- Follow tutorial on https://sonata-project.org/bundles/admin/3-x/doc/getting_started/creating_an_admin.html
- Create new `Category`
# Expected results
- Should be able to create `Category`
# Actual results
- Got error about CSRF token invalid

form with `var_dum[($_POST)` result

<img width="756" alt="screen shot 2016-06-01 at 10 12 16 am" src="https://cloud.githubusercontent.com/assets/223657/15696276/8bda7060-27e1-11e6-9433-2174ea6027cb.png">

**Comment by pulzarraider** [comment]
@gusdecool can you output also the $_SESSION and check if the token is stored in the session?

**Comment by gusdecool** [comment]
Hi @pulzarraider , here is the content of `$_SESSION` when i run it on `preValidate()` in `Admin` class

<img width="473" alt="screen shot 2016-06-07 at 8 18 29 am" src="https://cloud.githubusercontent.com/assets/223657/15842073/79b6b424-2c88-11e6-8f47-428670b3b47a.png">

looks like the token not there?

**Comment by Soullivaneuh** [comment]
@gusdecool Please stop use screenshot and use markdown code blocks instead: https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

Screenshot are not easier to read and is bad for search reference.

Could you also past you `Category` and `CategorAdmin` classes?

**Comment by gusdecool** [comment]
@Soullivaneuh 

```php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Category
 *
 * @ORM\Table(name="category")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CategoryRepository")
 */
class Category
{

    #----------------------------------------------------------------------------------------------
    # Properties
    #----------------------------------------------------------------------------------------------
    
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    #----------------------------------------------------------------------------------------------
    # Relation properties
    #----------------------------------------------------------------------------------------------

    /**
     * @var BlogPost[]
     * 
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\BlogPost", mappedBy="category")
     */
    private $blogPosts;

    #----------------------------------------------------------------------------------------------
    # Properties accessor
    #----------------------------------------------------------------------------------------------
    
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Category
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return BlogPost[]
     */
    public function getBlogPosts()
    {
        return $this->blogPosts;
    }

    /**
     * @param BlogPost[] $blogPosts
     * @return $this
     */
    public function setBlogPosts($blogPosts)
    {
        $this->blogPosts = $blogPosts;
        
        return $this;
    }
}
```

```php
<?php

namespace AppBundle\Admin;

use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;

/**
 * Class CategoryAdmin
 * @package AppBundle\Admin
 */
class CategoryAdmin extends AbstractAdmin
{

    /**
     * {@inheritdoc}
     */
    public function preValidate($object)
    {
        //var_dump($_SESSION);
    }

    #----------------------------------------------------------------------------------------------
    # Protected methods
    #----------------------------------------------------------------------------------------------

    /**
     * {@inheritdoc}
     */
    protected function configureFormFields(FormMapper $form)
    {
        $form->add('name', 'text');
    }

    /**
     * {@inheritdoc}
     */
    protected function configureDatagridFilters(DatagridMapper $filter)
    {
        $filter->add('name');
    }

    /**
     * {@inheritdoc}
     */
    protected function configureListFields(ListMapper $list)
    {
        $list->addIdentifier('name');
    }
}
```

**Comment by Soullivaneuh** [comment]
Can you please test again with the latest version of admin-bundle (`3.2.0`)?

Also please paste the result of `composer show sonata-project/*` and the `config.yml` content of key `framework`.

I can't reproduce the issue, it seems to be more a csrf misconfiguration.

Also, did you override any sonata class? Like `CRUDController` for example?

**Comment by j-ledoux** [comment]
I had the same issue when starting a new project using a docker container. I have installed Sonata admin 3.4.0 and Symfony 3.0.8. I solved it by leaving php handle the sessions regarding its configuration.

In `config.yml`, I replaced :
``` yaml
framework:
    session:
        handler_id:  session.handler.native_file
``` 
by
``` yaml
framework:
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
```

**Comment by Soullivaneuh** [comment]
@j-ledoux So you say replacing `session.handler.native_file` by `~` solves the issue?

In order to reproduce the bug, I tried:

```yaml
framework:
    session:
        handler_id:  session.handler.native_file
```

And it works fine for me... Are you sure it's the only change?

@gusdecool @j-ledoux Perhaps do you have some sonata admin templates overrides? If yes, could you please try without?

Also could you past your full `framework` configuration? Here is mine:

```yaml
framework:
    #esi:             ~
    translator:      { fallbacks: ['%locale%'] }
    secret:          '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path: '%kernel.root_dir%/sessions/%kernel.environment%'
        cookie_httponly: false
    fragments: ~
    http_method_override: true
```

**Comment by j-ledoux** [comment]
I didn't override any templates yet, it's a brand new project I've started yesterday.

I think it's related to my docker environment and session configuration. Symfony might not be able to handle session files properly. I noticed I have no folder named 'sessions' in my project root, symfony probably had permissions issues to create this folder.

Since I've changed the configuration file, I now have session files created in my `/tmp` container path and no more csrf token issue when posting forms.

Here is my `framework` configuration section, which is pretty much the default one besides `locale` and `session` conf:

``` yaml
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    default_locale:  "fr"
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        # handler_id:  session.handler.native_file # Not working with docker ?
        # save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        # cookie will last 24h
        cookie_lifetime: 86400
        # user can be inactive for 6h
        gc_maxlifetime: 21600
    fragments:       ~
    http_method_override: true
    assets:          ~
```
