### ISSUE TITLE
Impossible to set an icon for "on_top" element menu

### ISSUE THREAD

**Issue by Ximousse** [sonata-project/SonataAdminBundle#4023]
Before making a PR I wanted to make sure I'm not missing something:
when setting the option 'on_top' to true on an element of the menu, it is impossible to set an icon for this element:
#### Sonata packages

``` bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.4.0                    The missing Symfony Admin Generator
sonata-project/block-bundle              3.1.1                    Symfony SonataBlockBundle
sonata-project/cache                     1.0.7                    Cache library
sonata-project/core-bundle               3.0.3                    Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2                      Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2                    Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.0.5                    Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10                   Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.5.0                    Lightweight Exporter library
sonata-project/google-authenticator      1.0.2                    Library to integrate Google Authenticator into a PHP project
sonata-project/user-bundle               dev-rc_sf3tweaks bf121be Symfony SonataUserBundle
```
## Steps to reproduce

Fresh install of SonataAdmin, add the following config:

```yaml
sonata_admin:
  dashboard:
      groups:
          home:
            on_top: true
            icon: '<i class="fa fa-home"></i>'
            items:
              - route: sonata_admin_dashboard
                label: home
```
## Expected results

A nice "home" icon next to the element menu "home" in the left menu.
## Actual results

"Home" is there, but the icon is not (it is not a FontAwesome problem, the html is empty).
## Explanation

In sonata-project/admin-bundle/Resources/views/Menu/sonata_menu.html.twig:

``` twig
{% set icon = item.attribute('icon')|default(item.level > 1 ? '<i class="fa fa-angle-double-right"></i>' : '') %}
```

The html code for the icon is in this icon variable, but item.attribute() doesn't work.

Either my config is wrong or this line should be:

``` twig
{% set icon = item.extra('icon')|default(item.level > 1 ? '<i class="fa fa-angle-double-right"></i>' : '') %}
```

**Comment by Soullivaneuh** [comment]
Please first follow GitHub issue template for bug report.

**Comment by greg0ire** [comment]
Also, can you link to an explain the relevant piece of php code?

**Comment by Ximousse** [comment]
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.4.0                    The missing Symfony Admin Generator
sonata-project/block-bundle              3.1.1                    Symfony SonataBlockBundle
sonata-project/cache                     1.0.7                    Cache library
sonata-project/core-bundle               3.0.3                    Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2                      Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2                    Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.0.5                    Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10                   Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.5.0                    Lightweight Exporter library
sonata-project/google-authenticator      1.0.2                    Library to integrate Google Authenticator into a PHP project
sonata-project/user-bundle               dev-rc_sf3tweaks bf121be Symfony SonataUserBundle
```

## Steps to reproduce
Fresh install of SonataAdmin, add the following config:
```
sonata_admin:
  dashboard:
      groups:
          home:
            on_top: true
            icon: '<i class="fa fa-home"></i>'
            items:
              - route: sonata_admin_dashboard
                label: home
```
## Expected results
A nice "home" icon next to the element menu "home" in the left menu.

## Actual results
"Home" is there, but the icon is not (it is not a FontAwesome problem, the html is empty).

## Explanation
In sonata-project/admin-bundle/Resources/views/Menu/sonata_menu.html.twig:
```twig
{% set icon = item.attribute('icon')|default(item.level > 1 ? '<i class="fa fa-angle-double-right"></i>' : '') %}
```
The html code for the icon is in this icon variable, but item.attribute() doesn't work.

Either my config is wrong or this line should be:
```twig
{% set icon = item.extra('icon')|default(item.level > 1 ? '<i class="fa fa-angle-double-right"></i>' : '') %}
```

**Comment by greg0ire** [comment]
I edited your first message.

**Comment by ioweb-gr** [comment]
I just bumped into this issue while trying to achieve pretty much the same thing as @Ximousse but for me it's also not giving the correct route as well. 

```
sonata_admin:
  dashboard:
      groups:
          home:
            on_top: true
            icon: '<i class="fa fa-home"></i>'
            items:
              - route: sonata_admin_dashboard
                label: home
```

produces an `<a href="sonata_admin_dashboard">Home</a>` link instead of `/admin/dashboard` in my case and the home icon doesn't show either.

removing `on_top: true` yields the correct link 

@Ximousse  is the link also wrong for you besides the icon?

**Comment by Ximousse** [comment]
Yes, I wanted to create a separate issue for this but indeed the link is wrong (same as you).

**Comment by ioweb-gr** [comment]
Thank you @Ximousse for confirming, I tracked it down to 
`vendor/sonata-project/admin-bundle/Menu/Provider/GroupMenuProvider.php`

line 115
`$menuItem->setUri($item['route']);`

Seems the conditional if here 
`if (isset($item['admin']) && !empty($item['admin'])) {`
just sets the route as is in case the route is set in on_top = true groups where `admin` is not set

I don't know if it's by choice for some reason but I'd think that any route specified in config files should be set as a named route for consistency unless defined by another flag as relative or absolute path.

For my specific use case I changed 
`$item['route'] `
to 
`$this->pool->getContainer()->get('router')->generate($item['route']);`
and used your icon fix too temporarily and everything seems fine.

**Comment by greg0ire** [comment]
`$menuItem->setUri($item['route']);` definitely looks strange, and was introduced in #3159 by @tim96 . @tim96, can you please help?

**Comment by tim96** [comment]
> $menuItem->setUri($item['route']); definitely looks strange, and was introduced in #3159 by @tim96 . @tim96, can you please help?

@greg0ire no, I didn't remember. I created it PR a year ago, sorry.

**Comment by greg0ire** [comment]
> @greg0ire no, I didn't remember. I created it PR a year ago, sorry.

This is why we need unit tests…

@Ximousse @ioweb-gr , can you try `$menuItem->setExtra('route', $item['route']);` and report back?

**Comment by ioweb-gr** [comment]
@greg0ire 
it didn't help in my case

Using
```            Home:
              on_top: true
              icon: '<i class="fa fa-home"></i>'
              items:
                  - route: sonata_admin_dashboard
                    label: home
```

and replacing with 
`$menuItem->setExtra('route', $item['route'])`

yielded  a url of '#' but with the icon presented. My guess is it only presented the group but didn't render the actual menu item in the group

**Comment by OskarStark** [comment]
I can confirm this bug in my project:

```yaml
            sonata.admin.group.submit:
                label:              Submit
                label_catalogue:    messages
                icon:               '<i class="fa fa-arrow-right"></i>'
                on_top:             true
                items:
                    - route: admin_skus_submit
                      label: Submit
```

produces:
![screenshot 2017-05-19 09 09 01](https://cloud.githubusercontent.com/assets/995707/26236869/d4a6bc76-3c72-11e7-83c6-5bb06a240eb8.png)

So, no icon, and wrong target url.

When i use this:

```diff
            sonata.admin.group.submit:
                label:              Submit
                label_catalogue:    messages
                icon:               '<i class="fa fa-arrow-right"></i>'
-               on_top:             true
                items:
                    - route: admin_skus_submit
                      label: Submit
```

it generates an icon for the wrapper and the correct url:
![screenshot 2017-05-19 09 10 58](https://cloud.githubusercontent.com/assets/995707/26236913/192ade2c-3c73-11e7-96bf-482c07dcd012.png)
