### ISSUE TITLE
Checkbox on filter field is shown 20px left 

### ISSUE THREAD

**Issue by ahmetakbn** [sonata-project/SonataAdminBundle#4038]
#### Sonata packages

```bash
sonata-project/admin-bundle              3.4.0  The missing Symfony Admin Generator
sonata-project/block-bundle              3.1.1  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/cache-bundle              2.2.5  This bundle provides caching services
sonata-project/classification-bundle     3.1.0  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.0.3  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2    Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.0.5  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.6.0  Lightweight Exporter library
sonata-project/formatter-bundle          3.0.1  Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.2.4  Symfony SonataIntlBundle
sonata-project/media-bundle              3.1.0  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.0.0  Symfony SonataNotificationBundle
sonata-project/page-bundle               3.0.2  This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                2.0.2  Symfony SonataSeoBundle
sonata-project/timeline-bundle           3.0.0  Integrates SpyTimelineBundle into Sonata
sonata-project/user-bundle               3.0.1  Symfony SonataUserBundle
```

#### Symfony packages

```bash
symfony/assetic-bundle     v2.8.0  Integrates Assetic into Symfony2
symfony/monolog-bundle     2.11.1  Symfony MonologBundle
symfony/phpunit-bridge     v2.8.9  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.2.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.2.0  Symfony polyfill for intls ICU-related data and classes
symfony/polyfill-mbstring  v1.2.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.2.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.2.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.2.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.2.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.2.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.3.11 Symfony SwiftmailerBundle
symfony/symfony            v2.8.9  The Symfony PHP framework

```

#### PHP version

```bash
PHP 7.0.9-1+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.9-1+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
```

## Subject

Checkbox on filter field is shown 20 px left.

## Steps to reproduce
Add a checkbox field to filters

in `SonataAdminBundle/Resources/public/css/styles.css` checkbox has `margin-left : -20px` I could not understand why. But this causes that the checkbox is shown on filters 20 px left from where it supposed to shown.
```css
.checkbox div[class^="icheckbox"],
.checkbox-inline div[class^="icheckbox"],
.radio div[class^="iradio"],
.radio-inline div[class^="iradio"] {
    position: relative;
    margin-top: 4px \9;
    margin-left: -20px;
    margin-right: 5px;
    margin-top: -3px;
}
```

Shall I correct it by separating checkbox css and deleting this margin-left property?

**Comment by greg0ire** [comment]
Can you have a look at the history and discuss this with the author of this change?

**Comment by ahmetakbn** [comment]
@greg0ire yes sure.

**Comment by ahmetakbn** [comment]
@vincenttouzet I am having a problem when adding a checkbox filed on filter filed. It is 20 px on the left than where it supposed to be. I see that you added this in this PR :https://github.com/sonata-project/SonataAdminBundle/pull/3672 Can you please check this out why did you add `margin-left : -20px" to checkbox class in css?

**Comment by ahmetakbn** [comment]
When I put checkbox to filter filed here is the html output:
```html
<div class="checkbox">
    <div class="icheckbox_square-blue">
        <input type="checkbox" id="field_name" name="filter[field_name][value]" value="1" style="position: absolute; opacity: 0;">
        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins>
    </div>
</div>
```
On admin edit page html output for checkbox is like this:
```html
<div class="checkbox">
    <label class="">
        <div class="icheckbox_square-blue checked">
            <input type="checkbox" id="s57a09ed26cc49_growing" name="s57a09ed26cc49[growing]" class="" value="1" checked="checked" style="position: absolute; opacity: 0;">
            <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins>
        </div>
        <span class="control-label__text">"Wachsende" Sendung?</span>
    </label>
</div>
```
Checkbox on edit page has an extra `lavel` html entry. So my solution is move `margin-left: -20px`

From:
```css
/**
 * Make checkbox / radio label consistant with other labels
 */
.checkbox label,
.radio label {
    font-weight: 700;
}

/**
 * The iCheck checkboxes & radios have 0 margin by default,
 * add some space for the label text.
 */
.checkbox div[class^="icheckbox"],
.checkbox-inline div[class^="icheckbox"],
.radio div[class^="iradio"],
.radio-inline div[class^="iradio"] {
    position: relative;
    margin-top: 4px \9;
    margin-left: -20px;
    margin-right: 5px;
    margin-top: -3px;
}
```

To:
```css
/**
 * Make checkbox / radio label consistant with other labels
 */
.checkbox label,
.radio label {
    font-weight: 700;
    margin-left: -20px;
}

/**
 * The iCheck checkboxes & radios have 0 margin by default,
 * add some space for the label text.
 */
.checkbox div[class^="icheckbox"],
.checkbox-inline div[class^="icheckbox"],
.radio div[class^="iradio"],
.radio-inline div[class^="iradio"] {
    position: relative;
    margin-top: 4px \9;
    margin-right: 5px;
    margin-top: -3px;
}
```

This fixes the issue for checkbox on filter field.
