### ISSUE TITLE
Unrecognized option "breadcrumbs" under "sonata_admin"

### ISSUE THREAD

**Issue by rafrsr** [sonata-project/SonataAdminBundle#4094]
The following configuration does not work in brach 3.x like is described in the [documentation](https://sonata-project.org/bundles/admin/3-x/doc/reference/breadcrumbs.html)

``` yaml
# app/config/config.yml

sonata_admin:
    breadcrumbs:
       # use this to change the default route used to generate the link to the parent object inside a breadcrumb, when in a child admin
       child_admin_route: edit

```

Its posible customize the default route for parent object when in a child admin for only one admin?

parent/show/child/list
parent2/edit/child/list
parent3/edit/child/list

Currently I use `buildBreadcrumbs()` method but this method appear as deprecated, any other way?
