### ISSUE TITLE
Field type "sonata_type_collection" not saving the foreign key

### ISSUE THREAD

**Issue by alexandrubau** [sonata-project/SonataAdminBundle#4141]
Hi guys, I've ran in a bit of a problem with "sonata_type_collection" field type. Here's the story:

I have an entity entitled Game and an entity entitled Game Builds.
A Game can have multiple Game Builds (one-to-many).

In the administration page of the Game, I would like to also manage the builds.
I've thought the way to do this is through an **sonata_type_collection** field.
So in my *GameAdmin.php* page, in *configureFormFields* method I have the following:

```php
$formMapper
->with('Game builds')
->add('builds', 'sonata_type_collection', [
  'label' => false
], [
   'edit' => 'inline',
   'inline' => 'table'
 ])
->end();
```

After I add a new Game Build and save a Game, in the associative relation table called *game_builds* I see a row with the following columns:
`id=1, game_id=NULL, os_type=1, min_os_version=1.2.3`

Why doesn't it also populate the **game_id** column?
Here's a dump of the **$game** variable in the **preUpdate** method:
```
GameAdmin.php on line 291:
Game {#619 ▼
  -id: 1
  -title: "Pokemon Go"
  #locale: "en"
  #translations: PersistentCollection {#606 ▶}
  #link: null
  -builds: PersistentCollection {#578 ▼
    -snapshot: []
    -owner: Game {#619}
    -association: array:15 [ …15]
    -em: EntityManager {#1009 …11}
    -backRefFieldName: "game"
    -typeClass: ClassMetadata {#580 …}
    -isDirty: true
    #collection: ArrayCollection {#579 ▼
      -elements: array:1 [▼
        0 => GameBuild {#325 ▼
          -id: null
          -os_type: 1
          -min_os_version: "2"
          -game: null      <------------------------------------------------- I THINK THIS IS THE PROBLEM
        }
      ]
    }
    #initialized: true
  }
}
```

Game ORM:
```yaml
AppBundle\Entity\Game:
    type: entity
    table: games

    repositoryClass: AppBundle\Repository\GameRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        title:
            type: string

    lifecycleCallbacks: {  }

    oneToMany:
        builds:
            targetEntity: AppBundle\Entity\GameBuild
            mappedBy: game
            cascade: ["persist", "remove"]
            orphanRemoval: true
```

GameBuild ORM:
```yaml
AppBundle\Entity\GameBuild:
    type: entity
    table: game_builds

    repositoryClass: AppBundle\Repository\GameBuildRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        os_type:
            type: integer
        min_os_version:
            type: string

    lifecycleCallbacks: {  }

    manyToOne:
        game:
            targetEntity: AppBundle\Entity\Game
            inversedBy: builds
            joinColumn:
                name: game_id
                referencedColumnName: id
```

Thank you very much
