### ISSUE TITLE
ACL in SonataAdmin  

### ISSUE THREAD

**Issue by Carteni** [sonata-project/SonataAdminBundle#4190]
Hi guys,
i'm working with ACL in SonataAdmin, configs are all done but the dashboard is empty for a Guest User.
I'm not used SonataUserBundle because is not compatible).

Thanks.

```

Guest User Roles (from roles column in user table).
a:1:{i:0;s:24:"ROLE_APP_ADMIN_POST_LIST";}

// services.yml
app.admin.post:
        class: AppBundle\Admin\PostAdmin
        arguments: [~, AppBundle\Entity\Post, AppBundle:Admin/PostAdminCRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Blog Post"
        calls:
            - [addChild, ['@app.admin.comment']]

// app/config.yml
security:
   role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    
    acl:
        connection: default
    
    access_control:
         - { path: ^/admin, roles: [ROLE_USER] }

// app/config/sonata_admin.yml
parameters:
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

sonata_admin:
    ...
    dashboard:
        groups:
            app.admin.main:
                label: Content
                label_catalogue: AppBundle
                icon: '<i class="fa fa-th"></i>'
                items:
                    - app.admin.post
                    - app.admin.comment
            app.admin.media:
                label: Media
                label_catalogue: SonataMediaBundle
                icon: '<i class="fa fa-image"></i>'
                items:
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery
            app.admin.classification:
                label: Classification
                label_catalogue: SonataClassificationBundle
                icon: '<i class="fa fa-tags"></i>'
                items:
                    - sonata.classification.admin.tag
                    - sonata.classification.admin.category
                    - sonata.classification.admin.collection
                    - sonata.classification.admin.context
            app.admin.settings:
                label: Configuration
                label_catalogue: AppBundle
                icon: '<i class="fa fa-gear"></i>'
                items:
                    - route: config_myEdit
                      label: 'My Configuration'
                roles: [ ROLE_ADMIN, ROLE_SUPER_ADMIN ]
        
    security:
        handler: sonata.admin.security.handler.acl

        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            VIEW: VIEW
            DELETE: DELETE
            EXPORT: EXPORT
            MASTER: MASTER

        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]

        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
```

#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.9.0  The missing Symfony Admin G...
sonata-project/block-bundle              3.2.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/classification-bundle     3.1.0  Symfony SonataClassificatio...
sonata-project/core-bundle               3.1.1  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2    Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extens...
sonata-project/doctrine-orm-admin-bundle 3.1.1  Symfony Sonata / Integrate ...
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBu...
sonata-project/exporter                  1.7.0  Lightweight Exporter library
sonata-project/formatter-bundle          3.0.1  Symfony SonataFormatterBundle
sonata-project/intl-bundle               2.2.4  Symfony SonataIntlBundle
sonata-project/media-bundle              3.3.0  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.0.0  Symfony SonataNotificationB...
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/monolog-bundle     2.11.1 Symfony MonologBundle
symfony/phpunit-bridge     v3.1.6 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.2.0 Symfony polyfill backporting apcu_* funct...
symfony/polyfill-intl-icu  v1.2.0 Symfony polyfill for intl's ICU-related d...
symfony/polyfill-mbstring  v1.2.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.2.0 Symfony polyfill backporting some PHP 5.6...
symfony/polyfill-php70     v1.2.0 Symfony polyfill backporting some PHP 7.0...
symfony/polyfill-util      v1.2.0 Symfony utilities for portability of PHP ...
symfony/security-acl       v3.0.0 Symfony Security Component - ACL (Access ...
symfony/swiftmailer-bundle v2.4.0 Symfony SwiftmailerBundle
symfony/symfony            v3.1.6 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.11-1+deb.sury.org~trusty+1 (cli) ( NTS )
```
