### ISSUE TITLE
Make ROLE_SONATA_ADMIN (hardcoded in twig templates) configurable 

### ISSUE THREAD

**Issue by gremo** [sonata-project/SonataAdminBundle#4290]
In [`add_block.html.twig`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/Core/add_block.html.twig#L22) and [`standard_layout.html.twig`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/standard_layout.html.twig#L187) the role `ROLE_SONATA_ADMIN` is hardcoded. What about making it configurable?

This would allow us to configure a custom role i.e. the standard `ROLE_ADMIN` role, dropping the useless `ROLE_SONATA_ADMIN` role. Of course the default value would be the `ROLE_SONATA_ADMIN` for BC.

Example:

```yml
sonata_admin:
    # ...
    security:
        admin_role: ROLE_ADMIN
        admin_permission: # ...
```
