### ISSUE TITLE
Adding criteria to filter elements of an ArrayCollection shouldn't affect adding new items on CollectionType

### ISSUE THREAD

**Issue by FireLizard** [sonata-project/SonataAdminBundle#4346]
#### Sonata packages

```bash
sonata-project/admin-bundle              3.13.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.2.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
sonata-project/google-authenticator      1.0.2  Library to integrate Google Authenticator into a PHP project
sonata-project/translation-bundle        2.1.0  SonataTranslationBundle
sonata-project/user-bundle               3.2.1  Symfony SonataUserBundle
```

#### Symfony packages

```bash
symfony/monolog-bundle     2.11.3  Symfony MonologBundle
symfony/phpunit-bridge     v2.8.17 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.4.2  Symfony SwiftmailerBundle
symfony/symfony            v2.8.17 The Symfony PHP framework
```

#### PHP version

```bash
PHP 7.1.0 (cli) (built: Jan 17 2017 19:16:55) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

## Subject

Adding criteria to filter elements of an ArrayCollection shouldn't affect adding new items on CollectionType.

## Steps to reproduce

1. Create 2 entities **Event** and **Date** with _oneToMany_-association:
```php
<?php
namespace AppBundle\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;

class Event
{
    /**
     * @var ArrayCollection
     */
    protected $dates;

    public function __construct()
    {
        $this->dates = new ArrayCollection();
    }

    /**
     * @return ArrayCollection
     */
    public function getDates()
    {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->gte('dateTo', new DateTime()))
        ;

        // while this works ...
        // return $this->dates;

        // ... this does not work!
        return $this->dates->matching($criteria);
    }
}
```
```yml
AppBundle\Entity\Event:
    type: entity
    oneToMany:
        dates:
            targetEntity: AppBundle\Entity\Date
            mappedBy: event
            cascade: ["all"]
            orphanRemoval: true
            fetch: EXTRA_LAZY
            orderBy:
                datumVon: DESC
```
```php
<?php
namespace AppBundle\Entity;

use DateTime;

class Date
{
    /**
     * @var DateTime
     */
    private $dateTo;

    /**
     * @var Event
     */
    private $event;
   
    /** Getter & Setter */
}
```
```yml
AppBundle\Entity\Date:
    type: entity
    fields:
        dateTo:
            type: date
    manyToOne:
        event:
            targetEntity: AppBundle\Entity\Event
            inversedBy: dates
```
2. Create Admin for entity Event:
```php
<?php
namespace AppBundle\Admin;

use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\CoreBundle\Form\Type\CollectionType;

class EventAdmin extends AbstractAdmin
{
    /**
     * @param FormMapper $formMapper
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('dates', CollectionType::class, [
                'required' => true,
            ], [
                'edit' => 'inline',
                'inline' => 'table',
            ])
        ;
    }
}
```
```yml
admin.event:
        class: AppBundle\Admin\EventAdmin
        arguments: [~, AppBundle\Entity\Event, ~]
        tags:
            - { name: sonata.admin, manager_type: orm }
```
3. Go to editform.
## Expected results

I expected that changing `return $this->dates;` to `return $this->dates->matching($criteria);` (`Event::getDates()`) has no effect on frontend behaviour.

I want to get a new form to add a new **Date**-object by clicking on "+ New"-button (`<a class="sonata-ba-action" ... />`) ([sonata-type-collection](https://sonata-project.org/bundles/admin/3-x/doc/reference/form_types.html#sonata-type-collection)).

## Actual results

Got response body, but the loaded html is not showing up (not rendered in DOM?). The POST-Request responses with status code 200.
