### ISSUE TITLE
sonata_type_model_hidden not picking up related model

### ISSUE THREAD

**Issue by catharsisjelly** [sonata-project/SonataAdminBundle#4431]
#### Sonata packages

Just as a matter of note the below command did not work for me (composer 1.3.2), this is the output from `composer show | grep ^sonata`

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.13.0             The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.1              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/core-bundle               3.2.0              Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle 3.1.3              Symfony Sonata / Integrate Doctrine ORM int...
sonata-project/exporter                  1.7.1              Lightweight Exporter library
```

#### Symfony packages 

This is the output from `composer show | grep ^symfony`

```bash
$ composer show symfony/*
symfony/monolog-bundle                   2.12.0             Symfony MonologBundle
symfony/phpunit-bridge                   v3.1.7             Symfony PHPUnit Bridge
symfony/polyfill-apcu                    v1.3.0             Symfony polyfill backporting apcu_* functio...
symfony/polyfill-intl-icu                v1.3.0             Symfony polyfill for intl's ICU-related dat...
symfony/polyfill-mbstring                v1.3.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                   v1.3.0             Symfony polyfill backporting some PHP 5.6+ ...
symfony/polyfill-php70                   v1.3.0             Symfony polyfill backporting some PHP 7.0+ ...
symfony/polyfill-util                    v1.3.0             Symfony utilities for portability of PHP codes
symfony/security-acl                     v3.0.0             Symfony Security Component - ACL (Access Co...
symfony/swiftmailer-bundle               v2.4.0             Symfony SwiftmailerBundle
symfony/symfony                          v3.1.7             The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.15 (cli) (built: Jan 24 2017 19:06:16) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

## Subject

I'm trying to get SonataAdmin to create a model that is a OneToMany relationship and take the ID of the parent Model into the form. I have seen that there used to be a way in a previous version to get the Entity Manager and the related model but this now seems to be removed.

The documentation for this is lacking both [here](https://sonata-project.org/bundles/admin/master/doc/reference/action_create_edit.html) and [here](https://sonata-project.org/bundles/admin/master/doc/reference/form_types.html) where both gloss over it and we could do with some good concrete examples.

## Steps to reproduce

A Template has a OneToMany Relationship with Emails, models below

```php
/**
 * @ORM\Table(name="template")
 */
class Template
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", name="name")
     * @var string
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="Email", mappedBy="template")
     * @var Email[]
     */
    private $emails;
}
```

```php
/**
 * @ORM\Table(name="email")
 */
class Email
{

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Template", inversedBy="emails")
     * @ORM\JoinColumn(name="templateId", referencedColumnName="id")
     * @var Template
     */
    private $template;
}
```

These each have their own admin setup in `yml`

```yml
    admin.template:
        class: AppBundle\Admin\TemplateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: Templates, group: Templates, icon: <i class="fa fa-users"></i>}
        arguments:
            - ~
            - AppBundle\Entity\Template
            - ~
        calls:
            - [ addChild, ['@admin.email']]

    admin.email:
        class: AppBundle\Admin\EmailAdmin
        arguments:
            - ~
            - AppBundle\Entity\Email
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: Emails, group: Templates, icon: <i class="fa fa-users"></i>}
```

And have their own Admin classes

```php
class TemplateAdmin extends AbstractAdmin
{
/**
     * @param MenuItemInterface $menu
     * @param string $action
     * @param AdminInterface|null $childAdmin
     * @return bool
     */
    protected function configureTabMenu(MenuItemInterface $menu, $action, AdminInterface $childAdmin = null)
    {
        if (!$childAdmin && !in_array($action, ['edit'])) {
            return false;
        }

        $admin = $this->isChild() ? $this->getParent() : $this;
        $id = $admin->getRequest()->get('id');

        $menu->addChild(
            'Edit Template',
            [
                'uri' => $admin->generateUrl('edit', [
                    'id' => $id
                ])
            ]
        );

        $menu->addChild(
            'Emails',
            [
                'uri' => $admin->getRouteGenerator()->generate('admin_app_template_email_list', [
                    'id' => $id
                ])
            ]
        );
    }
}
```

```php
class EmailAdmin extends AdminBase
{
    /**
     * @var string
     */
    protected $baseRoutePattern = 'email';

    /**
     * @param FormMapper $formMapper
     * @return void
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper->add('subject', 'text', ['attr' => ["class" => "subject-input"]])
            ->add('template', 'sonata_type_model_hidden');
    }
}
```

## Expected results

In the `EmailAdmin` I am expecting the hidden `template` value to have a reference to the Template that was navigated from

## Actual results

No value is supplied to the hidden field

If I need to use `getNewInstance` can you give me an example of how to supply the information to it. I don't seem to be able to access the `EntityManager` from the `ModelManager` but could inject it into the `Admin` class if needed. I'm happy to update the docs if that will help too once a solution is provided.
