### ISSUE TITLE
jQuery UI dialog close button not showing

### ISSUE THREAD

**Issue by verheyenkoen** [sonata-project/SonataAdminBundle#4511]
#### Sonata packages

```
sonata-project/admin-bundle    3.18.2 The missing Symfony Admin Generator
sonata-project/block-bundle    3.3.2  Symfony SonataBlockBundle
sonata-project/cache           1.0.7  Cache library
sonata-project/core-bundle     3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle 2.2.1  Symfony SonataDatagridBundle
sonata-project/exporter        1.7.1  Lightweight Exporter library
```

#### Symfony packages

```
symfony/monolog-bundle     v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.2 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.3.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.2 Symfony SwiftmailerBundle
symfony/symfony            v3.3.2 The Symfony PHP framework
```

#### PHP version

```
PHP 5.6.30 (cli) (built: Mar 11 2017 09:56:27) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.3, Copyright (c) 2002-2017, by Derick Rethans
```

## Subject

When using a jQuery UI dialog in a Sonata Admin project, the close button "x" icon doesn't show.

This seems to be a [known problem](https://stackoverflow.com/a/20457891/192961) and can be solved by including the Bootstrap javascript file before the jQuery UI file, so simply [changing the order of these scripts](https://github.com/sonata-project/SonataAdminBundle/blob/466b047923416ce85bf9b6851f47d4aff6eefda3/DependencyInjection/Configuration.php#L366) (and updating the docs) should do it (if that doesn't bring any BC issues).

As a temp fix you can override the sonata_admin / assets / javascripts config section as defined here: https://sonata-project.org/bundles/admin/3-x/doc/reference/configuration.html

## Steps to reproduce

* Add an empty placeholder div
* Add some javascript to open the div as dialog, like so: `$('#some-div-selector').dialog();`

## Expected results

The close button "x" icon should be showing.

## Actual results

The close button "x" icon is not showing.

**Comment by OskarStark** [comment]
@verheyenkoen can you please provide a screenshot where it should be displayed?

**Comment by verheyenkoen** [comment]
Bad:

![image](https://user-images.githubusercontent.com/599538/27026450-16bc52b2-4f5e-11e7-9390-937aadb2d4ac.png)

Good:

![image](https://user-images.githubusercontent.com/599538/27026470-2240ab7e-4f5e-11e7-8fe1-af2acfbcccb9.png)

Notice the "x" icon in the top right corner of the dialog. 

You can easily trigger this behavior from the developer tools with console command:

```
$('section.content').dialog();
```

All I did between both screenshots was add the following to `config.yml`:

```
sonata_admin:
    assets:
        javascripts:
            - bundles/sonatacore/vendor/jquery/dist/jquery.min.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
            - bundles/sonatacore/vendor/moment/min/moment.min.js
            - bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
            - bundles/sonataadmin/vendor/jquery-form/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonatacore/vendor/select2/select2.min.js
            - bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js
            - bundles/sonataadmin/vendor/iCheck/icheck.min.js
            - bundles/sonataadmin/vendor/slimScroll/jquery.slimscroll.min.js
            - bundles/sonataadmin/vendor/waypoints/lib/jquery.waypoints.min.js
            - bundles/sonataadmin/vendor/waypoints/lib/shortcuts/sticky.min.js
            - bundles/sonataadmin/Admin.js
            - bundles/sonataadmin/treeview.js
```

... which is the default javascripts configuration (from the link mentioned above) where I just moved the bootsrap line above the jquery-ui line.
