### ISSUE TITLE
Documentation update - symfony 3.3 sets all services to public: false

### ISSUE THREAD

**Issue by mmucklo** [sonata-project/SonataAdminBundle#4538]
Documentation update:

symfony 3.3+ is defaulting all services to public: false (see configuration sample below)

From: [https://github.com/symfony/symfony-standard/blob/3.3/app/config/services.yml](https://github.com/symfony/symfony-standard/blob/3.3/app/config/services.yml)
```yaml
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
```

So the following documentation needs to be updated:

[https://sonata-project.org/bundles/admin/3-x/doc/getting_started/creating_an_admin.html](https://sonata-project.org/bundles/admin/3-x/doc/getting_started/creating_an_admin.html)
```yaml
# app/config/services.yml

services:
    # ...
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
```

So the documentation needs to be modified like this:

```yaml
# app/config/services.yml

services:
    # ...
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        public: true
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
```

Otherwise you'll get errors like this if you strictly follow the example in symfony 3.3:

```
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  You have requested a non-existent service "admin.category".
```
