### ISSUE TITLE
Wrong translation of links in the side menu

### ISSUE THREAD

**Issue by axzx** [sonata-project/SonataAdminBundle#4614]
#### Sonata packages

```
sonata-project/admin-bundle              3.22.0 3.22.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  1.0.7  Cache library
sonata-project/core-bundle               3.4.0  3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.1.6  3.1.6  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.1  1.7.1  Lightweight Exporter library
```

#### Symfony packages

```
symfony/monolog-bundle     v3.1.0 v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.6 v3.3.6 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.5.0 v1.5.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.5.0 v1.5.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.5.0 v1.5.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.5.0 v1.5.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.5.0 v1.5.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72     v1.5.0 v1.5.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util      v1.5.0 v1.5.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v3.0.3 v3.0.3 Symfony SwiftmailerBundle
symfony/symfony            v3.3.6 v3.3.6 The Symfony PHP framework
```

#### PHP version

```
PHP 7.0.22-0ubuntu0.17.04.1 (cli) (built: Aug  8 2017 22:03:30) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
    with Zend OPcache v7.0.22-0ubuntu0.17.04.1, Copyright (c) 1999-2017, by Zend Technologies
```

## Subject
After the recent changes are not translated links in the side menu.

Related PR:
#4601

Related commits:
2c4e0ba3a8348290c9f3dd45159b0319536c9e3b
bcdc4f7a0a8c735f87d48d57725e5f24676c665a

## Steps to reproduce
I define the service this way:

```yaml
custom_form.admin.bank_account:
        class: Custom\FormBundle\Admin\BankAccountAdmin
        arguments: [~, Custom\FormBundle\Entity\BankAccount, CustomAppBundle:BaseAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Form, label: Bank Account, label_catalogue: FormAdminBundle, show_mosaic_button: false}
        calls:
            - [setTranslationDomain, ["FormAdminBundle"]]
```

## Expected results
In menu: "Konto bankowe" 
(domain: FormAdminBundle.pl.yml)

## Actual results
In menu: "Bank Account" 
(domain: messages.pl.yml)
