### ISSUE TITLE
Sonata and Symfony 3.3+ new service system

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataAdminBundle#4710]
Symfony 3.3 comes with [several changes](http://symfony.com/doc/current/service_container/3.3-di-changes.html) on the DI system in order to simplify the configuration.

This is great, but absolutely not compatible with Sonata ATM.

I think we should take profit to simplify our admin definition too. I don't know yet if this will be BC or not.

I'll try to explain each issue, step by step.

## Current statement

Take this services as example:

```yaml
services:
    admin.user:
        class: AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: User, label: User, show_mosaic_button: true }
        arguments: [ ~, AppBundle\Entity\User, 'AppBundle:Admin/User' ]
        calls:
            - [setUserManager, ['@fos_user.user_manager']]
            - [setMailer, ['@mailer.legacy']]
            - [setTokenGenerator, ['@fos_user.util.token_generator']]

    admin.ssh_key:
        class: AppBundle\Admin\SshKeyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: User, label: SSH Key }
        arguments: [ ~, AppBundle\Entity\SshKey, ~ ]
```

Most of the tag options and services arguments are generally left untouched, except for group and label.

This may be simplified like this (and make it as default on the bundle):

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Sonata\AdminBundle\Admin\AdminInterface:
            tags: [ sonata.admin ]
```

But many things are missing:

* The `manager_type` needs a default value
* The group, the label and any another tag options are not provided anymore
* The required entity argument is not provided at all.

So I start to build a compiler pass on my project to simulate autoconfiguring:

```php
use Doctrine\Common\Inflector\Inflector;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

final class AdminCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        foreach ($container->findTaggedServiceIds('sonata.admin') as $id => $attributes) {
            $definition = $container->getDefinition($id);

            $adminClassTab = \explode('\\', $definition->getClass());
            $entityName = \preg_replace('/Admin$/', '', \end($adminClassTab));
            $definition
                ->clearTag('sonata.admin')
                ->addTag('sonata.admin', [
                    'manager_type' => 'orm',
                    'label' => Inflector::ucwords(\str_replace('_', ' ', Inflector::tableize($entityName))),
                ])
                ->setArguments([
                    null,
                    "AppBundle\\Entity\\{$entityName}",
                    null,
                ])
            ;
        }
    }
}

final class AppBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container);

        $container
            ->addCompilerPass(new AdminCompilerPass(), PassConfig::TYPE_BEFORE_OPTIMIZATION, 10)
        ;
    }
}
```

It works for my case even if it does not manage all the options (like the mosaic view for example), but this ran to another issue: The generated sonata role are now different:

![image](https://user-images.githubusercontent.com/1698357/31829206-e4e2f596-b5bc-11e7-887c-c8c875ae6641.png)

This is "normal" because the admin code is not provided and take the service name which is now the class name.

So I tried to replace the `null` code argument by `'admin.'.Inflector::tableize($entityName)` in order to get the old admin code and roles.

And then, this error:

![image](https://user-images.githubusercontent.com/1698357/31829350-47d2fb9c-b5bd-11e7-91cb-9aa4de58877d.png)

## Possible improvements

To simplify the service definition, we must:

* Have admin **tags** options defined on admin classes only. With properties and/or getter.
* Have some options/argument like the manager type, managed entity, Controllers or label guessed, based from the admin class name.

Obviously, some arguments may be still be overridden on the service definition.

Concerning the code, for now I don't get why it try to get the admin service with this.

I never used a custom admin code from now. What is the purpose of this comparing to the service name? Can this be be removed/simplified? Or maybe leave it as is and change how the sonata role are generated?

This is some ideas I got, feel free to add yours.

**Comment by greg0ire** [comment]
The purpose of the admin_code is IIRC to be able to have several admins for a same entity, and be able to specify it. I think we should simply drop it in favor of the class name.

**Comment by Soullivaneuh** [comment]
> The purpose of the admin_code is IIRC to be able to have several admins for a same entity, and be able to specify it.

Are you sure about that?

```
services:
    admin.ticket:
        class: AppBundle\Admin\TicketAdmin
        arguments: [ ~, AppBundle\Entity\Ticket, 'AppBundle:Admin/Ticket' ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Support, label: Ticket }

    admin.ticket_feedback:
        class: AppBundle\Admin\TicketFeedbackAdmin
        arguments: [ ~, AppBundle\Entity\Ticket, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Support, label: Ticket Feedback }
```

Two different admins, same targeted entity and no provided code.

Or maybe we are not talking about the same thing.
