### ISSUE TITLE
Is it possible to use new service declaration approach from symfony 4 (3.4) with sonata admin?

### ISSUE THREAD

**Issue by osavchenko** [sonata-project/SonataAdminBundle#4865]
I want to declare admin classes in one go and I declare it in `services.yml` like this:

```yaml
    App\Admin\Store\:
        resource: '../src/Admin/Store/*'
        arguments: [~, '', ~]
        tags:
            -
              name: sonata.admin
              manager_type: orm
              group: store
              label_translator_strategy: sonata.admin.label.strategy.underscore
              icon: '<i class="fa fa-archive"></i>'
        public: true
```

and in each admin class I do:

```php
class ProductAdmin extends AbstractAdmin
{
    /**
     * {@inheritdoc}
     */
    public function __construct(string $code, string $class, string $baseControllerName)
    {
        parent::__construct($code, Product::class, $baseControllerName);
    }

    /**
     * {@inheritdoc}
     */
    public function getLabel()
    {
        return 'products';
    }
```

So, looks like I have ready admin class, but when I'm using relations in admin classes I get some wired errors like on Mant-To-One relation with `ModelListType` field:
```
Twig_Error_Runtime:
Impossible to invoke a method ("id") on a null variable.

  at vendor\sonata-project\doctrine-orm-admin-bundle\src\Resources\views\Form\form_admin_fields.html.twig:59
  at twig_get_attribute(object(Twig_Environment), object(Twig_Source), null, 'id', array(null), 'method')
```

Maybe we can adopt admin bundle to use a new service declaration approach?
