### ISSUE TITLE
Creating an Admin on SonataAdminBundle and Symfony 4 Flex .In CheckExceptionOnInvalidReferenceBehaviorPass.php line 32:    The service "admin.category" has a dependency on a non-existent service "sonata.admin.manager.   orm".

### ISSUE THREAD

**Issue by pedramham** [sonata-project/SonataAdminBundle#5000]
I am using **Symfony 4 Flex**.I using this [tutorial](http://symfony.com/doc/master/bundles/SonataAdminBundle/getting_started/creating_an_admin.html) .

it is my  _config/routes/sonata_admin.yaml_

```
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
```
it is  my config/services.yaml
```
services:
    admin.category:
       class: App\Admin\CategoryAdmin
       arguments: [~, App\Entity\Category, ~]
       tags:
           - { name: sonata.admin, manager_type: orm, label: Category }
       public: true
```
when i run my app i have this error .Where is my mistake?
```
$ php bin/console server:run
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 32:

  The service "admin.category" has a dependency on a non-existent service "sonata.admin.manager.
  orm".
```
