### ISSUE TITLE
symfony Flex sonataAdminBundle :: CKEditor does not work

### ISSUE THREAD

**Issue by pedramham** [sonata-project/SonataAdminBundle#5027]
I am using **Symfony 3.4  Flex** with **SonataAdminbundle 3.33** .I'm going to use ckeditor for Textarea.
I used this [tutorial](https://sonata-project.org/bundles/formatter/master/doc/reference/installation.html)
But the ckeditor is not applying to the textarea as expected and i have normal textarea

this is my BlogPostAdmin
```
.
.
.
use Sonata\FormatterBundle\Form\Type\SimpleFormatterType;
class BlogPostAdmin extends AbstractAdmin
{
protected function configureFormFields(FormMapper $formMapper)
    {
.
.
.
   $formMapper ->add('description', SimpleFormatterType::class, array(
                'format' => 'markdown',
                'ckeditor_context' => 'default', // optional
            ));
.
.
.
    }
}
```

> I have already installed the SonataCoreBundle.And in the second step of [training ](https://sonata-project.org/bundles/formatter/master/doc/reference/installation.html#)Has been mentioned
> you must have sonata.yaml but i have sonata_admin.yaml .Is this a problem??

It is my sonata_admin.yaml

```
sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_formatter:
    default_formatter: text
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig #keep this commented unless you are using media bundle.


        text:
            service: sonata.formatter.text.text
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        rawhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        twig:
            service: sonata.formatter.text.twigengine
            extensions: [] # Twig formatter cannot have extensions


.
    }
}
```
and it is my ivory_ck_editor.yaml

```
ivory_ck_editor:
    default_config: default
    configs:
        default:
            toolbar:
                - ['Bold', 'Italic', 'Strike', 'Link']
                - ['BulletedList', 'NumberedList', '-', 'Outdent', 'Indent']
                - ['Copy', 'Paste', 'PasteFromWord', '-', 'Undo', 'Redo']
                - ['Source']
```

**Comment by pedramham** [comment]
I solved this problem.in sonata_admin.yaml I changed the following


```
sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    assets:
          extra_javascripts:
              - bundles/ivoryckeditor/ckeditor.js
              - bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js
              - bundles/sonataformatter/markitup/sets/markdown/set.js
              - bundles/sonataformatter/markitup/sets/html/set.js
              - bundles/sonataformatter/markitup/sets/textile/set.js

          extra_stylesheets:
              - bundles/sonataformatter/markitup/skins/sonata/style.css
              - bundles/sonataformatter/markitup/sets/markdown/style.css
              - bundles/sonataformatter/markitup/sets/html/style.css
              - bundles/sonataformatter/markitup/sets/textile/style.css
.
.
.....
```
