### ISSUE TITLE
Calling "addChild" without second argument is deprecated since 3.35

### ISSUE THREAD

**Issue by jmros** [sonata-project/SonataAdminBundle#5109]
I have 2 classes:

In the services.yml

```
    admin.factura:
        class: AppBundle\Admin\FacturaAdmin
        arguments: [~, AppBundle\Entity\Factura, AppBundle:FacturaAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Facturas }
        calls:
            - [ addChild, ['@admin.factura_detalle']]
```

```
class FacturaDetalleAdmin extends AbstractAdmin {

  protected $baseRouteName = 'factura_detalle';
  protected $baseRoutePattern = 'factura_detalle';
  protected $parentAssociationMapping = 'factura';
.....

```

```
class FacturaAdmin extends AbstractAdmin {

  protected $baseRouteName = 'factura';
  protected $baseRoutePattern = 'factura';

```
If i do  de official documentation instructions it not works.
https://sonata-project.org/bundles/admin/3-x/doc/reference/child_admin.html

I need to add "            - [ addChild, ['@admin.factura_detalle']]" but this is not compatible wihit symfony 4.0

**Comment by kunicmarko20** [comment]
You have to remove 

```

  protected $parentAssociationMapping = 'factura';
```

and add it to 

```
        calls:
            - [ addChild, ['@admin.factura_detalle', 'factura']]
```

**Comment by jmros** [comment]
I love you!!!!! really tnks!!!!

**Comment by OskarStark** [comment]
@kunicmarko20 we should add an yaml example in the docs, too

**Comment by kunicmarko20** [comment]
Yes, that would make it easier for people.

**Comment by jmros** [comment]
yes, the website documentation doesn't  works.

i found this in stack oveflow:
```
        calls:
            - [ addChild, ['@admin.factura_detalle', 'NAME_OF_CHILD']]
```

**Comment by greg0ire** [comment]
@jmros can you please make a PR to fix the docs?

**Comment by OskarStark** [comment]
I created PR #5115

**Comment by kunicmarko20** [comment]
Yes, it should be removed, can you make a PR, please?

**Comment by OskarStark** [comment]
Thanks for your Feedback

**Comment by johnpancoast** [comment]
Sure. simple enough pr. Will do it tmrw or wknd between work

**Comment by johnpancoast** [comment]
FYI, haven't forgotten this. Just been busy. Will update when I can.

**Comment by johnpancoast** [comment]
Sorry I couldn't help more/sooner. Would love to help more though.

On Aug 7, 2018 9:22 PM, "Oskar Stark" <notifications@github.com> wrote:

Thank you for coming back 👍
In the meantime I fixe this small docs!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/sonata-project/SonataAdminBundle/issues/5109#issuecomment-411279921>,
or mute the thread

**Comment by OskarStark** [comment]
> Sorry I couldn't help more/sooner. Would love to help more though.

No problem, every help is appreciated 👍

**Comment by quazardous** [comment]
hi guys

just to report that using 2 arguments with more than one child admin is not working...

```yaml
    admin.game:
        class: App\Admin\GameAdmin
        arguments: [~, App\Entity\Game, ~]
        calls:
            - [addChild, ['@admin.game_game_score', 'game']]
            - [addChild, ['@admin.game_game_reference', 'game']]
```
this leads to a strange doctrine error:

```
[Semantical Error] line 0, col 75 near 's_game WHERE': Error: Class App\Entity\Game has no association named game
```
