### ISSUE TITLE
Dashboard GROUPS with roles are treated with "AND"

### ISSUE THREAD

**Issue by andrewmy** [sonata-project/SonataAdminBundle#5128]
#### Sonata packages

```
sonata-project/admin-bundle              3.x-dev 82a4d6e dev-master 4b2e943 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1          3.12.1             Symfony SonataBlockBundle
sonata-project/cache                     2.0.1           2.0.1              Cache library
sonata-project/core-bundle               3.9.1           3.10.0             Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1           2.3.1              Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.x-dev ec1d2a6 dev-master 1468a90 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.9.0           1.9.0              Lightweight Exporter library
```

#### Symfony packages

```
Too much of it, 4.0.11 basically.
```

#### PHP version

```
PHP 7.2.6
```

## Subject

Dashboard groups with roles are treated with "AND"

## Steps to reproduce

```yaml
sonata_admin:
  dashboard:
    groups:
      app.admin.dashboard:
        label: app.admin.dashboard
        icon:  '<i class="fa fa-bar-chart-o"></i>'
        items:
          - route: sonata_admin_dashboard
            label: app.admin.dashboard
        roles: [ROLE_SYS_ADMIN, ROLE_CLIENT_ADMIN]
        on_top: true
```

## Expected results

Both ROLE_SYS_ADMIN and ROLE_CLIENT_ADMIN see the menu item.

## Actual results

Only a user with both roles sees the menu item.

Caused by https://github.com/sonata-project/SonataAdminBundle/pull/5086
