### ISSUE TITLE
May the dashboard be optionnal (... and redirect to an Admin)

### ISSUE THREAD

**Issue by RobinDev** [sonata-project/SonataAdminBundle#5297]
## Feature Request

Hello, 

What are you thinking about let the Dashboard (Admin HomePage) be optionnal ?

How ? Just by adding a config option (like `default_dashboard`) wich permit to set a Default Admin like Dashboard

If you are OK, i will submit a pull request adding this feature (i want it so i will dev it anyway).

Thanks for ur amazing job :)

**Comment by OskarStark** [comment]
I am against such an option.

This could be easily done on the implementation side like this:
_security.yml_
```yaml
security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # -> custom firewall for the admin area of the URL
        admin:
            context:            admin
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                default_target_path: /admin/default
```

`default_target_path: /admin/default`

then add a _DefaultController.php_
```php
<?php

namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    /**
     * @Configuration\Route("/admin/default", name="admin_default_route")
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function defaultRouteAction()
    {
        if ($this->get('security.authorization_checker')->isGranted('ROLE_PDM')) {
            return $this->redirectToRoute('admin_pdm_csv');
        }

        if ($this->get('security.authorization_checker')->isGranted('ROLE_LOGISTICS')) {
            return $this->redirectToRoute('admin_logistics_search_ean');
        }

        return $this->redirectToRoute('sonata_admin_dashboard');
    }
}
```

here you can do some special things, for example define default route for different ROLES.
