### ISSUE TITLE
Validation error on dashboard with sonata.admin.block.stats

### ISSUE THREAD

**Issue by GCalmels** [sonata-project/SonataAdminBundle#5457]
### Environment
Symfony 4.2.2

#### Sonata packages
sonata-project/admin-bundle              3.45.1 3.45.1 The missing Symfony A...
sonata-project/block-bundle              3.14.0 3.14.0 Symfony SonataBlockBu...
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.15.1 3.15.1 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.4.0  2.4.0  Symfony SonataDatagri...
sonata-project/doctrine-extensions       1.1.5  1.1.5  Doctrine2 behavioral ...
sonata-project/doctrine-orm-admin-bundle 3.8.1  3.8.1  Symfony Sonata / Inte...
sonata-project/exporter                  2.0.1  2.0.1  Lightweight Exporter ...
sonata-project/intl-bundle               2.5.0  2.5.0  Symfony SonataIntlBundle

#### PHP version
PHP 7.2

## Subject
One violation error on dashboard with stats block.

## Steps to reproduce
Add a block in `sonata_admin` package file :
```
blocks:
            -
                type: sonata.admin.block.stats
                position: top
                class: col-lg-6 col-xs-6
                settings:
                    code:  users
                    icon:  fa-list-alt
                    text:  users
                    color: bg-green
```
It will display a box on dashboard page but in sf toolbar, I have an error with my created form : _per_page is invalid : `This value is not valid`

In `Datagrid.php`, the form is automatically submitted, the field _per_page is present and the values pass to the form is ok : `"_per_page" => ["type" => null, "value" => 1000]`.

The violation is a `ConstraintViolation` caused by a `TransformationFailedException`
