### ISSUE TITLE
Wrong query on admin with entity inheritance type JOINED

### ISSUE THREAD

**Issue by FireLizard** [sonata-project/SonataAdminBundle#5487]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.48.0 3.48.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.15.0 3.15.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.16.2 3.16.2 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.5.0  3.0.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.2.0  1.2.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.8.3  3.8.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  2.0.1  2.0.1  Lightweight Exporter library
sonata-project/intl-bundle               2.5.0  2.5.0  Symfony SonataIntlBundle
sonata-project/translation-bundle        2.4.1  2.4.1  SonataTranslationBundle
sonata-project/user-bundle               4.3.0  4.3.0  Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
Restricting packages listed in "symfony/symfony" to "3.4.*"
symfony/asset                 v3.4.23 v3.4.23 Symfony Asset Component
symfony/browser-kit           v3.4.23 v3.4.23 Symfony BrowserKit Component
symfony/cache                 v3.4.23 v3.4.23 Symfony Cache component with PSR-6, PSR-16, and tags
symfony/class-loader          v3.4.23 v3.4.23 Symfony ClassLoader Component
symfony/config                v3.4.23 v3.4.23 Symfony Config Component
symfony/console               v3.4.23 v3.4.23 Symfony Console Component
symfony/contracts             v1.0.2  v1.0.2  A set of abstractions extracted out of the Symfony components
symfony/css-selector          v3.4.23 v3.4.23 Symfony CssSelector Component
symfony/debug                 v3.4.23 v3.4.23 Symfony Debug Component
symfony/dependency-injection  v3.4.23 v3.4.23 Symfony DependencyInjection Component
symfony/doctrine-bridge       v3.4.23 v3.4.23 Symfony Doctrine Bridge
symfony/dom-crawler           v3.4.23 v3.4.23 Symfony DomCrawler Component
symfony/dotenv                v3.4.23 v3.4.23 Registers environment variables from a .env file
symfony/event-dispatcher      v3.4.23 v3.4.23 Symfony EventDispatcher Component
symfony/expression-language   v3.4.23 v3.4.23 Symfony ExpressionLanguage Component
symfony/filesystem            v3.4.23 v3.4.23 Symfony Filesystem Component
symfony/finder                v3.4.23 v3.4.23 Symfony Finder Component
symfony/flex                  v1.2.0  v1.2.0  Composer plugin for Symfony
symfony/form                  v3.4.23 v3.4.23 Symfony Form Component
symfony/framework-bundle      v3.4.23 v3.4.23 Symfony FrameworkBundle
symfony/http-foundation       v3.4.23 v3.4.23 Symfony HttpFoundation Component
symfony/http-kernel           v3.4.23 v3.4.23 Symfony HttpKernel Component
symfony/inflector             v3.4.23 v3.4.23 Symfony Inflector Component
symfony/intl                  v3.4.23 v3.4.23 A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/maker-bundle          v1.11.5 v1.11.5 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/options-resolver      v3.4.23 v3.4.23 Symfony OptionsResolver Component
symfony/phpunit-bridge        v3.4.23 v4.2.4  Symfony PHPUnit Bridge
symfony/polyfill-apcu         v1.11.0 v1.11.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu     v1.11.0 v1.11.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn     v1.11.0 v1.11.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring     v1.11.0 v1.11.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72        v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/profiler-pack         v1.0.4  v1.0.4  A pack for the Symfony web profiler
symfony/property-access       v3.4.23 v3.4.23 Symfony PropertyAccess Component
symfony/property-info         v3.4.23 v3.4.23 Symfony Property Info Component
symfony/routing               v3.4.23 v3.4.23 Symfony Routing Component
symfony/security              v3.4.23 v3.4.23 Symfony Security Component
symfony/security-acl          v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle       v3.4.23 v3.4.23 Symfony SecurityBundle
symfony/serializer            v3.4.23 v3.4.23 Symfony Serializer Component
symfony/stopwatch             v3.4.23 v3.4.23 Symfony Stopwatch Component
symfony/swiftmailer-bundle    v3.2.5  v3.2.5  Symfony SwiftmailerBundle
symfony/templating            v3.4.23 v3.4.23 Symfony Templating Component
symfony/translation           v3.4.23 v3.4.23 Symfony Translation Component
symfony/twig-bridge           v3.4.23 v3.4.23 Symfony Twig Bridge
symfony/twig-bundle           v3.4.23 v3.4.23 Symfony TwigBundle
symfony/validator             v3.4.23 v3.4.23 Symfony Validator Component
symfony/var-dumper            v3.4.23 v3.4.23 Symfony mechanism for exploring and dumping PHP variables
symfony/web-profiler-bundle   v3.4.23 v3.4.23 Symfony WebProfilerBundle
symfony/webpack-encore-bundle v1.4.0  v1.4.0  Integration with your Symfony app & Webpack Encore!
symfony/yaml                  v3.4.23 v3.4.23 Symfony Yaml Component
```

#### PHP version

```
$ php -v
PHP 7.2.8 (cli) (built: Jul 21 2018 07:56:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.8, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
```

## Subject
I want to integrate the doctrine extension [Timestampable](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/timestampable.md).

But when using [Class Table Inheritance](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/inheritance-mapping.html#class-table-inheritance) the query generated by the admin of an extended entity is missing the corresponding fields.

## Steps to reproduce
1. Create two entities `App\Entity\Institution\Winery` and `App\Entity\AbstractInstitution`.
```
<?php declare(strict_types=1);

namespace App\Entity;

use Gedmo\Timestampable\Traits\Timestampable;

abstract class AbstractInstitution
{
    use Timestampable;

    protected $id;
}
```
```
<?php declare(strict_types=1);

namespace App\Entity\Institution;

class Winery extends \App\Entity\AbstractInstitution
{
}
```

2. Build inheritance
```
# config/doctrine/AbstractInstitution.orm.yml
App\Entity\AbstractInstitution:
    type: entity

    inheritanceType: JOINED
    discriminatorColumn:
        name: discriminator
        type: string

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
```
```
# config/doctrine/Institution.Winery.orm.yml
App\Entity\Institution\Winery:
    type: entity
```
3. Register Admins
```
# config/sonata_admin/services.yaml
services:
    App\Admin\Institution\Winery:
        class: App\Admin\Institution\WineryAdmin
        arguments: [~, App\Entity\Institution\Winery, ~]
        tags:
            - { name: sonata.admin, manager_type: orm }
        public: true
```
4. Enable timestampable
```
# config/packages/stof_doctrine_extensions.yaml
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
```

## Expected results
When entering the list view, something like this.
```
SELECT 
  a0_.id AS id_0, 
  a0_.created_at AS created_at_1, 
  a0_.updated_at AS updated_at_2
FROM 
  winery w1_ 
  INNER JOIN abstract_institution a0_ ON w1_.id = a0_.id 
```

## Actual results
```
SELECT 
  a0_.id AS id_0
FROM 
  winery w1_ 
  INNER JOIN abstract_institution a0_ ON w1_.id = a0_.id 
```

By using Single Table Inheritance its working as expected: the createdAt and updatedAt are shown in the list view.

Maybe you can help. Thanks for advice!
