### ISSUE TITLE
button css

### ISSUE THREAD

**Issue by axzx** [sonata-project/SonataAdminBundle#557]
my suggestion

``` css
.sonata-bc .btn{
    padding: 5px 4px 6px !important;
}
.sonata-bc .btn a{
    padding: 6px 7px !important;
}
```
