### ISSUE TITLE
Advanced extension tagging

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#6027]
## Feature Request

I would like to contribute a new feature which will extend the registration of admin extensions. 

At the moment you could only apply admin extensions by defining an extension config: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/docs/reference/extensions.rst#configuration or you could tag admin services with `global` or `target`.

My idea is to add new attributes (`extends`, `implements`, ...) to `sonata.admin.extension`. So that all admin which extend a specific interface / extend a specific class / ... would use the extension.

```
        services:
            app.sortable.extension:
                class: App\Admin\Extension\SortableAdminExtension
                tags:
                    - { name: sonata.admin.extension, instanceof: 'Acme\Model\SortableInterface' }
```
