### ISSUE TITLE
[RFC] Disable global search by admin

### ISSUE THREAD

**Issue by phansys** [sonata-project/SonataAdminBundle#6102]
## Feature Request
Currently, the only way to disable the global search for a whole admin is by setting the option `'global_search' => false` at all their text filters.

IMO, simplifying that task could be a great addition.
We could implement this feature with a service tag:
```yaml
my.admin:
    # ...
    tags:
        - { global_search: false, name: sonata.admin, manager_type: orm }
```
