### ISSUE TITLE
Add a way to define the prefered Admin for a specific Entity

### ISSUE THREAD

**Issue by quazardous** [sonata-project/SonataAdminBundle#6266]
## Feature Request

I know i can use `admin_code` to specify the admin to use when I create multiple Admin for an entity.

But it would be easier to add some property to the Admin class to define the precedence of admins.

```php

final class DefaultAdmin extends AbstractAdmin
{
    protected $priority = 0; //default
    ...
}

```

```php

final class OtherAdmin extends AbstractAdmin
{
    protected $priority = 999; // some technical admin because sometimes sub admin routes are picky
    ...
}

```

so in the Pool

```php

    public function getAdminByClass($class)
    {
        ...
        // the first one would/could be correct if no admin_code specified
        return $this->getInstance($this->adminClasses[$class][0]);
    }


```

**Comment by VincentLanglet** [comment]
Do you want to work on a Pr ?

**Comment by VincentLanglet** [comment]
When I think about it, maybe the priority is not the best way.

If admin A has a priority of 0, B a priority of 1, and C a priority of 2, C will always be taken, so it feel like it's useless to set a priority for B.

A boolean seems enough (primary ? Main ? ...)

**Comment by quazardous** [comment]
why not... have you some pointers ? I've looked around and some stuff are in the injection pass...

in addition this property must be tweakable in the service definition because sometimes we want to reuse admin class

```yaml

admin.cool:
        class: App\Admin\CoolAdmin
        arguments: [~, App\Entity\Cool, ~]

admin.cool_copy:
        class: App\Admin\CoolAdmin
        arguments: [~, App\Entity\Cool, ~]
        calls:
              - [setPriority, [999]]

```

**Comment by quazardous** [comment]
> Do you want to work on a Pr ?

Est-ce qu'il y a un dev startup kit ? / Is there a dev startup kit ?

**Comment by VincentLanglet** [comment]
Indeed, using the admin configuration seems a better idea than a class property.

If i remember correctly, there is a "display_in_dashboard" property in the config. (Default true). Maybe we could have something similar ?

> > Do you want to work on a Pr ?
> 
> 
> 
> Est-ce qu'il y a un dev startup kit ? / Is there a dev startup kit ?

Not sure what you're looking for. So i would say no. Just clone the projet, modify the code, add tests, and its ok.

**Comment by VincentLanglet** [comment]
Here, there is a `show_in_dashboard` property https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php

But maybe @sonata-project/contributors have a better idea than something like a `main` property in the admin config.

**Comment by wbloszyk** [comment]
IMHO new array config where user can set default admin for the entity. By default first register admin.

**Comment by quazardous** [comment]
> IMHO new array config where user can set default admin for the entity. By default first register admin.

Make sens using the order of declaration is way better than adding some arbitrary field

**Comment by VincentLanglet** [comment]
> > IMHO new array config where user can set default admin for the entity. By default first register admin.
> 
> Make sens using the order of declaration is way better than adding some arbitrary field

The order of declaration has already an impact about where the admin is displayed in the side-menu.

If I have three adminds for the same entity: foo, bar, baz.
- I want the order foo, bar, baz in the menu.
- I want the default one to be bar.
How will I be able to do, if the order has an impact about the default one ?

**Comment by quazardous** [comment]
> How will I be able to do, if the order has an impact about the default one ?

Good point too. But IMHO non default admins are often technical admins I don't want to show in side menu.

But we can have both, default value for `priority` set order of declaration and updatable with some conf param you mentioned earlier.

**Comment by wbloszyk** [comment]
> > How will I be able to do, if the order has an impact about the default one ?
> 
> Good point too. But IMHO non default admins are often technical admins I don't want to show in side menu.
> 
> But we can have both, default value for `priority` set order of declaration and updatable with some conf param you mentioned earlier.

You should configure by dashbord group config. We taking about admina where admin_code is not set.

**Comment by quazardous** [comment]
> You should configure by dashbord group config. We taking about admina where admin_code is not set.

I don't understand, can you provide a use case ?

**Comment by VincentLanglet** [comment]
> > How will I be able to do, if the order has an impact about the default one ?
> 
> Good point too. But IMHO non default admins are often technical admins I don't want to show in side menu.

My project use lot of non-default admins which are display on the side menu. So this can't be considered as a general rule.

**Comment by quazardous** [comment]
> But we can have both, default value for `priority` set by order of declaration and updatable with some conf param you mentioned earlier

I'm keeping this one. Is it ok ?

for the name

entity_precedence ?

entity_affinity ?

entity_priority ?

Lesser numbers will have priority

**Comment by VincentLanglet** [comment]
> > But we can have both, default value for `priority` set by order of declaration and updatable with some conf param you mentioned earlier
> 
> I'm keeping this one. Is it ok ?
> 
> for the name
> 
> entity_precedence ?
> 
> entity_affinity ?
> 
> entity_priority ?
> 
> Lesser numbers will have priority

See https://github.com/sonata-project/SonataAdminBundle/issues/6266#issuecomment-671061587
What would be the advantage of priority over a simple boolean ?

We could add something like a `main` conf param.
```
App\Admin\FooAdmin:
        arguments:
            - ~
            - App\Entity\Foo
            - ~
        tags:
            - name: sonata.admin
              manager_type: orm
              group: foo
              label: foo
              show_in_dashboard: true
              main: true

App\Admin\Foo2Admin:
        arguments:
            - ~
            - App\Entity\Foo
            - ~
        tags:
            - name: sonata.admin
              manager_type: orm
              group: foo
              label: foo
              show_in_dashboard: true
```

And for the implementation, you'll need to modify this case
```
if (\count($this->adminClasses[$class]) > 1) {
            throw new \RuntimeException(sprintf(
                'Unable to find a valid admin for the class: %s, there are too many registered: %s',
                $class,
                implode(', ', $this->adminClasses[$class])
            ));
        }
```
With the logic:
- If there is no main, change the exception for "You should define a main admin"
- If there is multiple main, change the exception for "Too many main"
- else return the only main
