### ISSUE TITLE
Allow use other layout like AdminLTE 3

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/SonataAdminBundle#6388]
For now we use AdminLTE2 based on bootstrap 3. After add `webpack` tools to create new custom layout we should add new options for AdminBundle too. My idea is add options:
```yaml
sonata_admin:
    layout: admin_lte2 # admin_lte2 or admin_lte3
    custom_layouts:
        my_custom_layout: dir_to_files
```
Information about layout will be add to TemplateRegistry. New files for supported layouts will be add in `Resources/views/layouts`.

## TODO
- [ ] add new options
- [ ] implements layout option in TemplateRegistry
- [ ] ~~create~~ copy admin_lte3 files to `Resources/views/layouts/admin_lte3`
- [ ] add documentation about experimental feature (this change can be done in 3.x branch)
