### ISSUE TITLE
Use CSS images and CSS classes more often than normal images

### ISSUE THREAD

**Issue by pulzarraider** [sonata-project/SonataAdminBundle#641]
In default template I see normal images used in many places - for example boolean value in List is rendered with this code:

``` html
<img src="{{ asset('bundles/sonataadmin/famfamfam/accept.png') }}" alt="{%- trans from 'SonataAdminBundle' %}label_type_yes{% endtrans -%}" />
```

I think, the code would be easily extendable, if the image will be rendered using CSS.

``` html
<span class="sonata-list-type-boolean">
    <span class="sonata-list-type-boolean-text">
    {%- trans from 'SonataAdminBundle' %}label_type_yes{% endtrans -%}
    </span>
</span>
```

``` css
.sonata-list-type-boolean {
     background: transparent url('relative/path/to/image') top left no-repeat;
     width: 24px;
     height: 24px;
    display: block;
}
.sonata-list-type-boolean-text {
    display: none;
}
```

After this change, only the CSS should be created to overload some visual changes of default template and no custom template is needed. CSS images can be also combined to one and used as CSS sprites. This can speed up the performance of administration.

This changes can be applied on any images in List, Dashboard and other places.
