### ISSUE TITLE
ACL bypassed with Batch Action

### ISSUE THREAD

**Issue by tristanbes** [sonata-project/SonataAdminBundle#648]
Hi,

I've just setup ACL and i've granted an admin to edit 1 Object (let's say Article).

If i go to the User Admin or Category admin, i can't edit/delete them (the buttons next to the object are not here)
**BUT**
If i check all the users and then i hit the Batch delete, **i bypass the ACL and i successfully manage to delete all users**.

Is that a vulnerability ? A bug ? Or a configuration problem ?

``` yml
sonata_admin:
    title:     MyProject
    title_logo: /bundles/bund/images/aelogo.png
    templates:
        layout: ::admin.html.twig
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR]
            ADMIN:    [MASTER]

        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, OPERATOR, MASTER, OWNER]

```

Currently, the user which is allowed to manage the object "Article" has a `ROLE_ADMIN`
There are `ROLE_SUPER_ADMIN` for super admin who can do everything (as AdminBundle defines it)

Thanks.

Using Symfony 2.1 and master branch SonataAdminBundle
