### ISSUE TITLE
Create a TaggedAdminTrait instead of the AbstractTaggedAdmin and move AbstractAdmin construct arguments to the sonata.admin tag

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#6723]
The `sonata.admin` tag requires
- a specific constructor signature
- a lot of setters

The AbstractTaggedAdmin class has all these setters and the constructor signature. If we could stop to rely on the constructor signature, we could stop using the AbstractTaggedAdmin class and use a trait with all the getters/setters instead.

For this, we should move from this admin declaration
```
admin.category:
    class: App\Admin\CategoryAdmin
    arguments: [CustomCode, App\Entity\Category, CustomController::class]
    tags:
        - { name: sonata.admin, manager_type: orm, label: Category }
``` 
To this one
```
admin.category:
    class: App\Admin\CategoryAdmin
    tags:
        - { name: sonata.admin, class: App\Entity\Category, controller: CustomController::class, code: CustomCode, manager_type: orm, label: Category }
```
