### ISSUE TITLE
Autoconfigure admin services

### ISSUE THREAD

**Issue by kirya-dev** [sonata-project/SonataAdminBundle#6891]
## Feature Request

Im would like autoconfigure admin services with the next configuration:

```yml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Admin\:
        resource: '../../Admin/*Admin.php'
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin }
```

```php
class ProductAdmin extends AbstractAdmin
{
    public function __construct()
    {
        parent::__construct('my-code', Product::class);
    }
}
```

But now im getting error (Non declared arguments in ProductAdmin) 
![image](https://user-images.githubusercontent.com/30481080/109118104-ed2be580-7753-11eb-8df7-08367407160f.png)
