### ISSUE TITLE
Disable global search by admin options does not work

### ISSUE THREAD

**Issue by Byidi** [sonata-project/SonataAdminBundle#7510]
The disable global search by admin option introduced in [#6609](https://github.com/sonata-project/SonataAdminBundle/pull/6609) does not seems to have any effects.

`AdminSearchCompilerPass` set the index of the `adminSearch` table with the `id` of the tagged admin (https://github.com/sonata-project/SonataAdminBundle/blob/f26feb598e32d194aa3ad82609bb1a27ebcd67e5/src/DependencyInjection/Compiler/AdminSearchCompilerPass.php#L51).

However, the `SearchHandler` look for `$admin->getCode()` as index: https://github.com/sonata-project/SonataAdminBundle/blob/f26feb598e32d194aa3ad82609bb1a27ebcd67e5/src/Search/SearchHandler.php#L44

services.yaml :
```yaml

  App\Admin\Entity1:
    tags:
      - name: sonata.admin
        global_search: false
  App\Admin\Entity2:
    tags:
      - name: sonata.admin
        global_search: false
```

adminSearch dump:
```php
array:2 [▼
  "App\Admin\Entity1" => false
  "App\Admin\Entity2" => false
]
```

$admin->getCode() dump
```admin.entity1```

### Environment
```
sonata-project/admin-bundle              3.105.0           
sonata-project/block-bundle              3.23.0            
sonata-project/cache                     2.1.1             
sonata-project/core-bundle               3.20.0            
sonata-project/doctrine-extensions       1.12.0            
sonata-project/doctrine-orm-admin-bundle 3.35.0            
sonata-project/exporter                  2.6.2             
sonata-project/form-extensions           0.1.2             
sonata-project/intl-bundle               2.7.0             
sonata-project/twig-extensions           0.1.1 
```
```
symfony 4.4
```
