### ISSUE TITLE
Use Sonata Admin for data coming from REST API

### ISSUE THREAD

**Issue by cezar77** [sonata-project/SonataAdminBundle#7534]
## Feature Request

An Admin class must be registered as a service like this:

```
# config/services.yaml

services:
    # ...
    admin.category:
        class: App\Admin\CategoryAdmin
        arguments: [~, App\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category } 
```

It requires an entity as second argument and either `orm` or `odm` passed as value to the `manager_type` tag.

I have a specific case where part of the data we're dealing with comes from a REST API. It would be great if we could build a client inside Sonata Admin to communicate with the RESTful service and display the data.
We use Guzzle to make HTTP requests to the REST API.

Would it be possible to create a custom `manager_type` and plug it in instead of `orm` or `odm`?

Is my use case too specific, or are there maybe other people interested in a feature like this.

An entity that maps the REST API endpoint would be still required, but not persisted into a database.
