### ISSUE TITLE
Routing problem

### ISSUE THREAD

**Issue by remontees** [sonata-project/SonataAdminBundle#775]
When I register a UserAdmin in the config.yml, I've this problem :
Cannot import resource "/var/www/Symfony/app/config/." from "/var/www/Symfony/app/config/routing.yml".
500 Internal Server Error - FileLoaderLoadException

The service section in the config.yml :

```
services:
    admin.user:
        class: Rms\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: General, label: Authors }
        arguments: [null, Rms\UserBundle\Entity\User, SonataAdminBundle:CRUD]
```

And the routing.yml file :

```
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
```
