### ISSUE TITLE
Cannot override final method AbstractAdmin->getDataSourceIterator() 

### ISSUE THREAD

**Issue by lbcd** [sonata-project/SonataAdminBundle#7805]
Before we could override this function getDataSourceIterator() in Admin classes. 
Now after an update of sonata admoin I can't do it anymore. It can't be overrided as it is marked as "final" in parent.

So how can I update my source to bypass this BC break ?

**Comment by VincentLanglet** [comment]
In 4.x getDataSourceIterator is final.

You can implement your own https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Exporter/DataSourceInterface.php
and configure your admin to use your custom service instead of the default one.

**Comment by lbcd** [comment]
Thank you @VincentLanglet. 

How can I configure my admin to use my custom service instead of the default one? 

Should I use $this->setDataSource(); in the constructor or is there a better way?

**Comment by VincentLanglet** [comment]
Take a look at https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/advanced_configuration/#service-configuration

I won't say more to see if the doc is good enough or if a PR is needed to improve it.

**Comment by lbcd** [comment]
I understand a good way to have a good doc.

Was not easly to understand the doc. And when I think I have understand it doesn't work.

I create a service:
```
    admin.user_purchase.datasource:
        class: Admin\Services\UserPuchaseDatasource 
```

Here is my Datasource file : 
```
final class UserPuchaseDatasource implements DataSourceInterface
{
    public function createIterator(ProxyQueryInterface $query, array $fields): SourceIteratorInterface
    {
        die('Work ?');
    }
}
```

Then I add it to my Admin service :
```
    admin.user_purchase:
        class: Admin\UserPurchaseAdmin
        arguments:
           ...
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: "Admin.UserPurchase"
                data_source: "admin.user_purchase.datasource"
```


But the die never append. And I don't have any error.

**Comment by VincentLanglet** [comment]
> Was not easly to understand the doc.

Any suggestion is welcomed :) 

```
    admin.user_purchase:
        class: Admin\UserPurchaseAdmin
        arguments:
           ...
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: "Admin.UserPurchase"
                data_source: "admin.user_purchase.datasource"
```
This should work IMHO.

The die should only happen when the `createIterator` is called, so when you're trying to export something.
If not, you could try to debug call getSourceIterator() on the admin to know which class is loaded.
