### ISSUE TITLE
Env variable to define sonata_admin.options.skin

### ISSUE THREAD

**Issue by ec-ecss** [sonata-project/SonataAdminBundle#8014]
## Feature Request
I am on admin-bundle 4.9
The config variable sonata_admin.options.skin needs a constant string
Is it possible to make it customizable with a environnement variable ?
Currently a "%env(SOMETHING)% is not functionnal and an exception about a empty string is triggered

**Comment by haivala** [comment]
Pass it to service parameter first and then use that

**Comment by ec-ecss** [comment]
Hello thank you very much for your answer. 
I'm so sorry... but could you just specify what is the service you talk about, and  "it" and "that" ? It's not clear for me... I know well sf, but not sonata.

**Comment by haivala** [comment]
in parameters.yml
```
parameters:
     skin: "env..
```
and then in sonata_admin.yml you should be able to access that with `%skin%`

https://symfonycasts.com/screencast/symfony5-fundamentals/parameters#reading-parameters-in-config-files

**Comment by ec-ecss** [comment]
Tx. I've tried :


``` yaml
parameters:
  app_skin: '%env(APP_SKIN)%'
sonata_admin:
  title: '%env(APP_TITLE)%'
  dashboard:
    blocks:
      - { type: sonata.admin.block.admin_list, position: left }
  title_logo: '%env(APP_LOGO)%'
  options:
    skin: '%app_skin%'
```

But still got error
The value "" is not allowed for path "sonata_admin.options.skin". Permissible values: "skin-black", etc...

Obviously the APP_SKIN is well defined in .env.local
```
APP_SKIN='skin-red-light'
```
