### ISSUE TITLE
Rebuild template layer

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/SonataAdminBundle#8117]
## Feature Request

Current system have one template (AdminLTE2) and it is depends of some bundle config. This solution is hard to keep BC becouse depends of so many third part packages. 

Now all templates are taken from `sonata.admin.global_template_registry`. Some `sonata_admin.options` should be move there. Also templateRegistry should be moved to pool. This solution will make templates replaceable without BC break.

From this:
``` 
sonata_admin:
    options:
        skin: 'skin-black'
        use_select2: true
        use_icheck: true
        use_bootlint: false
        use_stickyforms: true

    templates:
        user_block: '@SonataAdmin/Core/user_block.html.twig'
        ....
        knp_menu_template: '@SonataAdmin/Menu/sonata_menu.html.twig'
        form_theme: []
        filter_theme: []
```
To this:
``` 
sonata_admin:
    default_template: adminlte2
    templates:
        adminlte2:
            user_block: '@SonataAdmin/Core/user_block.html.twig'
            ....
            knp_menu_template: '@SonataAdmin/Menu/sonata_menu.html.twig'
            form_theme: []
            filter_theme: []
            options:
                skin: 'skin-black'
                use_select2: true
                use_icheck: true
                use_bootlint: false
                use_stickyforms: true
        bootstrap5: # adminLTE3, tabler, or any otherr
            user_block: '@JonDoeAdmin/Core/user_block.html.twig'
            ....
            knp_menu_template: '@JonDoeAdmin/Menu/sonata_menu.html.twig'
            form_theme: []
            filter_theme: []
            options:
                skin: 'black'
        another_custom_template:
            ....
```
