### ISSUE TITLE
Different lists for one model

### ISSUE THREAD

**Issue by qwebot** [sonata-project/SonataAdminBundle#826]
hi!
How can i create two different lists for one model? In my case i have one model User. And for this model in my dashboard i must have two lists: Members and Admins. I create for members:

```
sonata.admin.members:
    class: Project\AdminBundle\Admin\MemberAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, model_manager: sonata.admin.manager.project, group: Members, label: Members}
    arguments: [null, %fos_user.model.user.class%, SonataAdminBundle:CRUD]
    calls:
      - [setTranslationDomain, [ProjectUserBundle]]
```

and for admins:

```
sonata.admin.user:
    class: Project\UserBundle\Admin\UserAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, model_manager: sonata.admin.manager.project, group: Admins, label: Admin Users}
    arguments: [null, %fos_user.model.user.class%, ProjectUserBundle:CRUD]
    calls:
      - [setTranslationDomain, [ProjectUserBundle]]
```

So, i have two tabs in admin panel, but it has one url, and work only with one Admin class. 

Any ideas?
