### ISSUE TITLE
Symfony2+SonataAdminBundle: Exception: […]some missing mandatory parameters (“id”)

### ISSUE THREAD

**Issue by Defcon0** [sonata-project/SonataAdminBundle#839]
Hello,

I have problems opening some item in some admin listview (i.e. /app_dev.php/de/admin/acme/hello/userlogin/1/edit):

An exception has been thrown during the rendering of a template ("The "admin_acme_hello_userlogin_edit" route has some missing mandatory parameters ("id").") in AcmeHelloBundle::layout.html.twig at line 44.

Unfortunately I don't see anything problematically in line 44 of the twig (seems that the error message's got the wrong line).

routing.yml:

```
_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /{_locale}/admin
  defaults: { _locale: de }

sonata_user:
  resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
  prefix: /{_locale}/admin
  defaults: { _locale: de }
```

I think the problem here is that I extended some templates, i.e.:

AcmeHelloBundle::layout.html.twig -> extends AcmeHelloBaseBundle::layout.html.twig

layout.html.twig from HelloBundle is my default layout-template:

sonata_admin:
    templates:
        # default global templates
        layout:  HelloBundle:Hello:layout.html.twig

When I replace my layout.html.twig by the default one, it works. Ain't it ok to do such an inheriting?

Big thanks in advance!!

Bye Defcon0
