### ISSUE TITLE
strange with labels

### ISSUE THREAD

**Issue by nucleartux** [sonata-project/SonataAdminBundle#956]
I've installed the latest Sonata admin bundle on symfony 2.1 and got the following problem:
![strange labels](http://i.stack.imgur.com/wzeiJ.png)

config.yml:

```
services:
  app.geo.admin.city:
      class: App\GeoBundle\Admin\CityAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Гео данные, label: Города}
      arguments: [null, App\GeoBundle\Entity\City, SonataAdminBundle:CRUD]
```

Admin class:
    <?php
    namespace App\GeoBundle\Admin;

```
class CityAdmin extends Admin
{
    public function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('name', null, array('required' => true))
            ->add('code')
            ->add('region')
            ->add('crest', 'file', array('required' => false))
            ->add('banner', 'file', array('required' => false))
            ->add('sort')
        ;
    }
}
```
